# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeoGuru' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod "PCLBlurEffectAlert"
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'SwiftyStoreKit'
  pod 'Alamofire'

end
