//
//  Capitals.swift
//  
//
//  Created by Keshav Ramesh on 10/8/18.
//

import UIKit

class Capitals: NSObject{
  let unitedstatesCapitals: [[String]] = [
        ["Alabama", "Montgomery"],
        ["Alaska", "Juneau"],
        ["Arizona", "Phoenix"],
        ["Arkansas", "Little Rock"],
        ["California", "Sacramento"],
        ["Colorado", "Denver"],
        ["Connecticut", "Hartford"],
        ["Delaware", "Dover"],
        ["Florida", "Tallahassee"],
        ["Georgia", "Atlanta"],
        ["Hawaii", "Honolulu"],
        ["Idaho", "Boise"],
        ["Illinois", "Springfield"],
        ["Indiana", "Indianapolis"],
        ["Iowa", "Des Moines"],
        ["Kansas", "Topeka"],
        ["Kentucky", "Frankfort"],
        ["Louisiana", "Baton Rouge"],
        ["Maine", "Augusta"],
        ["Maryland", "Annapolis"],
        ["Massachusetts", "Boston"],
        ["Michigan", "Lansing"],
        ["Minnesota", "Saint Paul"],
        ["Mississippi", "Jackson"],
        ["Missouri", "Jefferson City"],
        ["Montana", "Helena"],
        ["Nebraska", "Lincoln"],
        ["Nevada", "Carson City"],
        ["New Hampshire", "Concord"],
        ["New Jersey", "Trenton"],
        ["New Mexico", "Santa Fe"],
        ["New York", "Albany"],
        ["North Carolina", "Raleigh"],
        ["North Dakota", "Bismarck"],
        ["Ohio", "Columbus"],
        ["Oklahoma", "Oklahoma City"],
        ["Oregon", "Salem"],
        ["Pennsylvania", "Harrisburg"],
        ["Rhode Island", "Providence"],
        ["South Carolina", "Columbia"],
        ["South Dakota", "Pierre"],
        ["Tennessee", "Nashville"],
        ["Texas", "Austin"],
        ["Utah", "Salt Lake City"],
        ["Vermont", "Montpelier"],
        ["Virginia", "Richmond"],
        ["Washington", "Olympia"],
        ["West Virginia", "Charleston"],
        ["Wisconsin", "Madison"],
        ["Wyoming", "Cheyenne"]
    ]
    
   let countryCapitals: [[String]] = [
        ["Abkhazia", "Sukhumi"],
        ["Afghanistan", "Kabul"],
        ["Akrotiri and Dhekelia", "Episkopi Cantonment"],
        ["Aland Islands", "Mariehamn"],
        ["Albania", "Tirana"],
        ["Algeria", "Algiers"],
        ["American Samoa", "Pago Pago"],
        ["Andorra", "Andorra la Vella"],
        ["Angola", "Luanda"],
        ["Anguilla", "The Valley"],
        ["Antigua and Barbuda", "St. John's"],
        ["Argentina", "Buenos Aires"],
        ["Armenia", "Yerevan"],
        ["Artsakh", "Stepanakert"],
        ["Aruba", "Oranjestad"],
        ["Australia", "Canberra"],
        ["Austria", "Vienna"],
        ["Azerbaijan", "Baku"],
        ["Bahamas", "Nassau"],
        ["Bahrain", "Manama"],
        ["Bangladesh", "Dhaka"],
        ["Barbados", "Bridgetown"],
        ["Belarus", "Minsk"],
        ["Belgium", "Brussels"],
        ["Belize", "Belmopan"],
        ["Benin (legislative capital)", "Porto-Novo"],
        ["Benin (de facto seat of government)", "Cotonou"],
        ["Bermuda", "Hamilton"],
        ["Bhutan", "Thimphu"],
        ["Bolivia (judicial capital)", "Sucre"],
        ["Bolivia (legislative capital)", "La Paz"],
        ["Bonaire", "Kralendijk"],
        ["Bosnia and Herzegovina", "Sarajevo"],
        ["Botswana", "Gaborone"],
        ["Brazil", "Brasilia"],
        ["British Virgin Islands", "Road Town"],
        ["Brunei", "Bandar Seri Begawan"],
        ["Bulgaria", "Sofia"],
        ["Burkina Faso", "Ouagadougou"],
        ["Burundi", "Bujumbura"],
        ["Cambodia", "Phnom Penh"],
        ["Cameroon", "Yaounde"],
        ["Canada", "Ottawa"],
        ["Cape Verde", "Praia"],
        ["Cayman Islands", "George Town"],
        ["Central African Republic", "Bangui"],
        ["Chad", "N'Djamena"],
        ["Chile", "Santiago"],
        ["China", "Beijing"],
        ["Christmas Island", "Flying Fish Cove"],
        ["Cocos (Keeling) Islands", "West Islands"],
        ["Colombia", "Bogota"],
        ["Comoros", "Moroni"],
        ["Cook Islands", "Avarua"],
        ["Republic of the Congo", "Brazzaville"],
        ["Costa Rica", "San Jose"],
        ["Croatia", "Zagreb"],
        ["Cuba", "Havana"],
        ["Curacao", "Willemstad"],
        ["Cyprus", "Nicosia"],
        ["Czech Republic (Czechia)", "Prague"],
        ["Democratic Republic of the Congo", "Kinshasa"],
        ["Denmark", "Copenhagen"],
        ["Djibouti", "Djibouti"],
        ["Dominica", "Roseau"],
        ["Dominican Republic", "Santo Domingo"],
        ["Ecuador", "Quito"],
        ["Egypt", "Cairo"],
        ["El Salvador", "San Salvador"],
        ["Equatorial Guinea", "Malabo"],
        ["Eritrea", "Asmara"],
        ["Estonia", "Tallinn"],
        ["Ethiopia", "Addis Ababa"],
        ["Falkland Islands", "Stanley"],
        ["Faroe Islands", "Torshavn"],
        ["Fiji", "Suva"],
        ["Finland", "Helsinki"],
        ["France", "Paris"],
        ["French Guiana", "Cayenne"],
        ["French Polynesia", "Papeete"],
        ["Gabon", "Libreville"],
        ["Gambia", "Banjul"],
        ["Georgia", "Tbilisi"],
        ["Germany", "Berlin"],
        ["Ghana", "Accra"],
        ["Gibraltar", "Gibraltar"],
        ["Greece", "Athens"],
        ["Greenland", "Nuuk"],
        ["Grenada", "St. George's"],
        ["Guadeloupe", "Basse-Terre"],
        ["Guam", "Hagatna"],
        ["Guatemala", "Guatemala City"],
        ["Guernsey", "Saint Peter Port"],
        ["Guinea", "Conakry"],
        ["Guinea-Bissau", "Bissau"],
        ["Guyana", "Georgetown"],
        ["Haiti", "Port-au-Prince"],
        ["Honduras", "Tegucigalpa"],
        ["Hungary", "Budapest"],
        ["Iceland", "Reykjavik"],
        ["India", "New Delhi"],
        ["Indonesia", "Jakarta"],
        ["Iran", "Tehran"],
        ["Iraq", "Baghdad"],
        ["Ireland", "Dublin"],
        ["Isle of Man", "Douglas"],
        ["Israel", "Jerusalem"],
        ["Italy", "Rome"],
        ["Ivory Coast (administrative)", "Yamoussoukro"],
        ["Ivory Coast (de facto seat of government)", "Abidjan"],
        ["Jamaica", "Kingston"],
        ["Japan", "Tokyo"],
        ["Jersey", "Saint Helier"],
        ["Jordan", "Amman"],
        ["Kazakhstan", "Astana"],
        ["Kenya", "Nairobi"],
        ["Kiribati", "South Tarawa"],
        ["North Korea", "Pyongyang"],
        ["South Korea", "Seoul"],
        ["Kosovo", "Pristina"],
        ["Kuwait", "Kuwait City"],
        ["Kyrgyzstan", "Bishkek"],
        ["Laos", "Vientiane"],
        ["Latvia", "Riga"],
        ["Lebanon", "Beirut"],
        ["Lesotho", "Maseru"],
        ["Liberia", "Monrovia"],
        ["Libya", "Tripoli"],
        ["Liechtenstein", "Vaduz"],
        ["Lithuania", "Vilnius"],
        ["Luxembourg", "Luxembourg"],
        ["Macedonia", "Skopje"],
        ["Madagascar", "Antananarivo"],
        ["Malawi", "Lilongwe"],
        ["Malaysia (legislative)", "Kuala Lumpur"],
        ["Malaysia (adminstrative)", "Putrajaya"],
        ["Maldives", "Male"],
        ["Mali", "Bamako"],
        ["Malta", "Valletta"],
        ["Marshall Islands", "Majuro"],
        ["Martinique", "Fort-de-France"],
        ["Mauritania", "Nouakchott"],
        ["Mauritius", "Port Louis"],
        ["Mayotte", "Mamoudzou"],
        ["Mexico", "Mexico City"],
        ["Federated States of Micronesia", "Palikir"],
        ["Moldova", "Chisinau"],
        ["Monaco", "Monaco"],
        ["Mongolia", "Ulaanbaatar"],
        ["Montenegro", "Podgorica"],
        ["Montserrat", "Brades"],
        ["Morocco", "Rabat"],
        ["Mozambique", "Maputo"],
        ["Myanmar", "Naypyidaw"],
        ["Namibia", "Windhoek"],
        ["Nauru", "Yaren"],
        ["Nepal", "Kathmandu"],
        ["Netherlands", "Amsterdam"],
        ["New Caledonia", "Noumea"],
        ["New Zealand", "Wellington"],
        ["Nicaragua", "Managua"],
        ["Niger", "Niamey"],
        ["Nigeria", "Abuja"],
        ["Niue", "Alofi"],
        ["Norfolk Island", "Kingston"],
        ["Northern Cyprus", "Lefkosa"],
        ["Northern Mariana Islands", "Saipan"],
        ["Norway", "Oslo"],
        ["Oman", "Muscat"],
        ["Pakistan", "Islamabad"],
        ["Palau", "Ngerulmud"],
        ["Palestine (administrative)", "Ramallah"],
        ["Palestine (disputed)", "East Jerusalem"],
        ["Panama", "Panama City"],
        ["Papua New Guinea", "Port Moresby"],
        ["Paraguay", "Asuncion"],
        ["Peru", "Lima"],
        ["Philippines", "Manila"],
        ["Pitcairn Islands", "Adamstown"],
        ["Poland", "Warsaw"],
        ["Portugal", "Lisbon"],
        ["Puerto Rico", "San Juan"],
        ["Qatar", "Doha"],
        ["Reunion", "Saint-Denis"],
        ["Romania", "Bucharest"],
        ["Russia", "Moscow"],
        ["Rwanda", "Kigali"],
        ["Saba", "The Bottom"],
        ["Sahrawo Arab Democratic Republic (Western Sahara)", "Tifariti"],
        ["Saint Barthelemy", "Gustavia"],
        ["Saint Helena, Ascension, and Tristan da Cunha", "Jamestown"],
        ["Saint Kitts and Nevis", "Basseterre"],
        ["Saint Lucia", "Castries"],
        ["Saint Martin", "Marigot"],
        ["Saint Pierre and Miquelon", "Saint-Pierre"],
        ["Saint Vincent and the Grenadines", "Kingstown"],
        ["Samoa", "Apia"],
        ["San Marino", "San Marino"],
        ["Sao Tome and Principe", "Sao Tome"],
        ["Saudi Arabia", "Riyadh"],
        ["Senegal", "Dakar"],
        ["Serbia", "Belgrade"],
        ["Seychelles", "Victoria"],
        ["Sierra Leone", "Freetown"],
        ["Singapore", "Singapore"],
        ["Sint Eustatius", "Oranjestad"],
        ["Sint Maarten", "Philipsburg"],
        ["Slovakia", "Bratislava"],
        ["Slovenia", "Ljubljana"],
        ["Solomon Islands", "Honiara"],
        ["Somalia", "Mogadishu"],
        ["Somaliland", "Hargeisa"],
        ["South Africa (administrative)", "Pretoria"],
        ["South Africa (legislative)", "Cape Town"],
        ["South Africa (judicial)", "Bloemfontein"],
        ["South Georgia and the South Sandwich Islands", "King Edward Point"],
        ["South Ossetia", "Tshkinvali"],
        ["South Sudan", "Juba"],
        ["Spain", "Madrid"],
        ["Sri Lanka (administrative)", "Sri Jayawardenepura Kotte"],
        ["Sri Lanka (commercial)", "Colombo"],
        ["Sudan", "Khartoum"],
        ["Suriname", "Paramaribo"],
        ["Svalbard", "Longyearbyen"],
        ["Swaziland (eSwatini), (admininstrative)", "Mbabane"],
        ["Swaziland (eSwatini), (legislative)", "Lobamba"],
        ["Sweden", "Stockholm"],
        ["Switzerland", "Bern"],
        ["Syria", "Damascus"],
        ["Taiwan", "Taipei"],
        ["Tajikistan", "Dushanbe"],
        ["Tanzania (legislative)", "Dodoma"],
        ["Tanzania (de facto seat of government)", "Dar es Salaam"],
        ["Thailand", "Bngkok"],
        ["East Timor (Timor-Leste)", "Dili"],
        ["Togo", "Lome"],
        ["Tokelau", "Atafu"],
        ["Tonga", "Nuku'alofa"],
        ["Transnistria", "Tiraspol"],
        ["Trindad and Tobago", "Port of Spain"],
        ["Tunisia", "Tunis"],
        ["Turkey", "Ankara"],
        ["Turkmenistan", "Ashgabat"],
        ["Turks and Caicos Islands", "Cockburn Town"],
        ["Tuvalu", "Funafuti"],
        ["Uganda", "Kampala"],
        ["Ukraine", "Kiev"],
        ["United Arab Emirates", "Abu Dhabi"],
        ["United Kingdom", "London"],
        ["United States", "Washington, D.C."],
        ["United States Virgin Islands", "Charlotte Amalie"],
        ["Uruguay", "Montevideo"],
        ["Uzbekistan", "Tashkent"],
        ["Vanuatu", "Port Vila"],
        ["Vatican City", "Vatican City"],
        ["Venezuela", "Caracas"],
        ["Vietnam", "Hanoi"],
        ["Wallis and Futuna", "Mata-Utu"],
        ["Yemen", "Sana'a"],
        ["Zambia", "Lusaka"],
        ["Zimbabwe", "Harare"]
    ]


//THE TITLES OF ALL OF THESE SHOULD JUST BE THE COUNTRY - for example, if it says "Indian Subdivision Capitals", the corresponding bar in the app should just say "India", because it will be under the bar titled "Foreign Subdivision Capitals"
    
    //  Afghanistan Subdivision Capitals
    let afghanistanCapitals: [[String]] = [
        ["Badakhshan", "Fayzabad"],
        ["Badghis", "Qala-i-Naw"],
        ["Baghlan", "Pul-e Khomri"],
        ["Balkh", "Mazar-i Sharif"],
        ["Bamyan", "Bamyan"],
        ["Daykundi", "Nili"],
        ["Farah", "Farah"],
        ["Faryab", "Maymana"],
        ["Ghazni", "Ghazni"],
        ["Ghor", "Chaghcharan"],
        ["Helmand", "Lashkargah"],
        ["Herat", "Herat"],
        ["Jowzjan", "Sheberghan"],
        ["Kabul", "Kabul"],
        ["Kandahar", "Kandahar"],
        ["Kapisa", "Mahmud-i-Raqi"],
        ["Khost", "Khost"],
        ["Kunar", "Asadabad"],
        ["Kunduz", "Kunduz"],
        ["Laghman", "Mihtarlam"],
        ["Logar", "Pul-i-Alam"],
        ["Nangarhar", "Jalalabad"],
        ["Nimruz", "Zaranj"],
        ["Nuristan", "Parun"],
        ["Paktia", "Gardez"],
        ["Paktika", "Sharana"],
        ["Panjshir", "Bazarak"],
        ["Parwan", "Charikar"],
        ["Samangan", "Samangan"],
        ["Sar-e Pol", "Sar-e Pol"],
        ["Takhar", "Taloqan"],
        ["Urozgan", "Tarinkot"],
        ["Wardak", "Maidan Shar"],
        ["Zabul", "Qalat"]
    ]
    
    //  Argentina Subdivision Capitals
    let argentinaCapitals: [[String]] = [
        ["Buenos Aires", "La Plata"],
        ["Catamarca", "San Fernando del Valle de Catamarca"],
        ["Chaco", "Resistencia"],
        ["Chubut", "Rawson"],
        ["Ciudad Autonoma de Buenos Aires", "Buenos Aires"],
        ["Cordoba", "Cordoba"],
        ["Corrientes", "Corrientes"],
        ["Entre Rios", "Parana"],
        ["Formosa", "Formosa"],
        ["Jujuy", "San Salvador de Jujuy"],
        ["La Pampa", "Santa Rosa"],
        ["La Rioja", "La Rioja"],
        ["Mendoza", "Mendoza"],
        ["Misiones", "Posadas"],
        ["Neuquen", "Neuquen"],
        ["Rio Negro", "Viedma"],
        ["Salta", "Salta"],
        ["San Juan", "San Juan"],
        ["San Luis", "San Luis"],
        ["Santa Cruz", "Rio Gallegos"],
        ["Santa Fe", "Santa Fe"],
        ["Santiago del Estero", "Santiago del Estero"],
        ["Tierra del Fuego", "Ushuaia"],
        ["Tucuman", "San Miguel de Tucuman"]
    ]
    
    //  Australia Subdivision Capitals
    let australiaCapitals: [[String]] = [
        ["Australian Capital Territory", "Canberra"],
        ["Jervis Bay Territory", "Jervis Bay Village"],
        ["New South Wales", "Sydney"],
        ["Northern Territory", "Darwin"],
        ["Queensland", "Brisbane"],
        ["South Australia", "Adelaide"],
        ["Tasmania", "Hobart"],
        ["Victoria", "Melbourne"],
        ["Western Australia", "Perth"]
    ]
    
    //  Bangladehs Subdivision Capitals
    let bangladeshCapitals: [[String]] = [
        ["Barisal", "Barisal"],
        ["Chittagong", "Chittagong"],
        ["Dhaka", "Dhaka"],
        ["Khulna", "Khulna"],
        ["Mymensingh", "Mymensingh"],
        ["Rajshahi", "Rajshahi"],
        ["Rangpur", "Rangpur"],
        ["Sylhet", "Sylhet"]
    ]
    
    //  Brazilian Subdivision Capitals
    let brazilCapitals: [[String]] = [
        ["Acre", "Rio Branco"],
        ["Alagoas", "Maceio"],
        ["Amapa", "Macapa"],
        ["Amazonas", "Manaus"],
        ["Bahia", "Salvador"],
        ["Ceara", "Fortaleza"],
        ["Distrito Federal", "Brasilia"],
        ["Espirito Santo", "Vitoria"],
        ["Goias", "Goiania"],
        ["Maranhao", "Sao Luis"],
        ["Mato Grosso", "Cuiaba"],
        ["Mato Grosso do Sul", "Campo Grande"],
        ["Minas Gerais", "Belo Horizonte"],
        ["Para", "Belem"],
        ["Paraiba", "Joao Pessoa"],
        ["Parana", "Curitiba"],
        ["Pernambuco", "Recife"],
        ["Piaui", "Teresina"],
        ["Rio de Janeiro", "Rio de Janeiro"],
        ["Rio Grande do Norte", "Natal"],
        ["Rio Grande do Sul", "Porto Alegre"],
        ["Rondonia", "Rio Branco"],
        ["Roraima", "Boa Vista"],
        ["Santa Catarina", "Florianopolis"],
        ["Sao Paulo", "Sao Paulo"],
        ["Sergipe", "Aracaju"],
        ["Tocantins", "Palmas"]
    ]
    
    //  Canada Subdivision Capitals
    let canadaCapitals: [[String]] = [
        ["Alberta", "Edmonton"],
        ["British Columbia", "Victoria"],
        ["Manitoba", "Winnipeg"],
        ["New Brunswick", "Fredericton"],
        ["Newfoundland and Labrador", "St. John's"],
        ["Northwest Territories", "Yellowknife"],
        ["Nova Scotia", "Halifax"],
        ["Nunavut", "Iqaluit"],
        ["Ontario", "Toronto"],
        ["Prince Edward Island", "Charlottetown"],
        ["Quebec", "Quebec City"],
        ["Saskatchewan", "Regina"],
        ["Yukon", "Whitehorse"]
    ]
    
    //  Chile Subdivision Capitals
    let chileCapitals: [[String]] = [
        ["Arica and Parinacota", "Arica"],
        ["Tarapaca", "Iquique"],
        ["Antofagasta", "Antofagasta"],
        ["Atacama", "Copiapo"],
        ["Coquimbo", "La Serena"],
        ["Valparaiso", "Valparaiso"],
        ["Santiago", "Santiago"],
        ["O'Higgins", "Rancagua"],
        ["Maule", "Talca"],
        ["Nuble", "Chillan"],
        ["Biobio", "Concepcion"],
        ["Araucania", "Temuco"],
        ["Los Rios", "Valdivia"],
        ["Los Lagos", "Puerto Montt"],
        ["Aysen", "Coihaique"],
        ["Magallanes", "Punta Arenas"]
    ]
    
    //  China Subdivision Capitals
    let chinaCapitals: [[String]] = [
         ["Anhui", "Hefei"],
         ["Beijing", "Beijing"],
         ["Chongqing", "Chongqing"],
         ["Fujian", "Fuzhou"],
         ["Gansu", "Lanzhou"],
         ["Guangdong", "Guangzhou"],
         ["Guangxi", "Nanning"],
         ["Guizhou", "Guiyang"],
         ["Hainan", "Haikou"],
         ["Hebei", "Shijiazhuang"],
         ["Heilongjiang", "Harbin"],
         ["Henan", "Zhengzhou"],
         ["Hong Kong", "Hong Kong"],
         ["Hubei", "Wuhan"],
         ["Hunan", "Changsha"],
         ["Inner Mongolia", "Hohhot"],
         ["Jiangsu", "Nanjing"],
         ["Jiangxi", "Nanchang"],
         ["Jilin", "Changchun"],
         ["Liaoning", "Shenyang"],
         ["Macau", "Macau"],
         ["Ningxia", "Yinchuan"],
         ["Qinghai", "Xining"],
         ["Shaanxi", "Xi'an"],
         ["Shandong", "Jinan"],
         ["Shanghai", "Shanghai"],
         ["Shanxi", "Taiyuan"],
         ["Sichuan", "Chengdu"],
         ["Taiwan", "Taipei"],
         ["Tianjin", "Tianjin"],
         ["Tibet", "Lhasa"],
         ["Xinjiang", "Urumqi"],
         ["Yunnan", "Kunming"],
         ["Zhejiang", "Hangzhou"]
    ]
    
    //  Cuba Subdivision Capitals
    let cubaCapitals: [[String]] = [
        ["Camaguey", "Camaguey"],
        ["Ciego de Avila", "Ciego de Avila"],
        ["Cienfuegos", "Cienfuegos"],
        ["La Habana", "La Habana"],
        ["Granma", "Bayamo"],
        ["Guantanamo", "Guantanamo"],
        ["Holguin", "Holguin"],
        ["Isla de la Juventud", "Nueva Gerona"],
        ["Artemisa", "Artemisa"],
        ["Las Tunas", "Las Tunas"],
        ["Matanzas", "Matanzas"],
        ["Mayabeque", "San Jose de las Lajas"],
        ["Pinar del Rio", "Pinar del Rio"],
        ["Sancti Spiritus", "Sancti Spiritus"],
        ["Santiago de Cuba", "Santiago de Cuba"],
        ["Villa Clara", "Santa Clara"]
    ]
    
    // Democratic Republic of the Congo Subdivision Capitals
    let democraticrepublicofthecongoCapitals: [[String]] = [
        ["Bas-Uele", "Buta"],
        ["Equateur", "Mbandaka"],
        ["Haut-Katanga", "Lubumbashi"],
        ["Haut-Lomami", "Kamina"],
        ["Haut-Uele", "Isiro"],
        ["Ituri", "Bunia"],
        ["Kasai", "Luebo"],
        ["Kasai-Central", "Kananga"],
        ["Kasai-Oriental", "Mbuji-Mayi"],
        ["Kinshasa", "Kinshasa"],
        ["Kongo Central", "Matadi"],
        ["Kwango", "Kenge"],
        ["Kwilu", "Kikwit"],
        ["Lomami", "Kabinda"],
        ["Lualaba", "Kolwezi"],
        ["Mai-Ndombe", "Inongo"],
        ["Maniema", "Kindu"],
        ["Mongola", "Lisala"],
        ["Nord-Ubangi", "Gbadolite"],
        ["North Kivu", "Goma"],
        ["Sankuru", "Lusambo"],
        ["South Kivu", "Bukavu"],
        ["Sud-Ubangi", "Gemena"],
        ["Tanganyika", "Kalemie"],
        ["Tshopo", "Kisangani"],
        ["Tshuapa", "Boende"]
    ]
    
    //  Ecuador Subdivision Capitals
    let ecuadorCapitals: [[String]] = [
        ["Azuay", "Cuenca"],
        ["Bolivar", "Guaranda"],
        ["Canar", "Azogues"],
        ["Carchi", "Tulcan"],
        ["Chimborazo", "Riobamba"],
        ["Cotopaxi", "Latacunga"],
        ["El Oro", "Machala"],
        ["Esmeraldas", "Esmeraldas"],
        ["Galapagos", "Puerto Baquerizo Moreno"],
        ["Guayas", "Guayaquil"],
        ["Imbabura", "Ibarra"],
        ["Loja", "Loja"],
        ["Los Rios", "Babahoyo"],
        ["Manabi", "Portoviejo"],
        ["Morona Santiago", "Macas"],
        ["Napo", "Tena"],
        ["Orellana", "Puerto Francisco de Orellana"],
        ["Pastaza", "Puyo"],
        ["Pichincha", "Quito"],
        ["Santa Elena", "Sana Elena"],
        ["Santo Domingo de los Tsachilas", "Santo Domingo de los Colorados"],
        ["Sucumbios", "Nueva Loja"],
        ["Tungurahua", "Ambato"],
        ["Zamora-Chinchipe", "Zamora"]
    ]
    
    //  Ethiopia Subdivision Capitals
    let ethiopiaCapitals: [[String]] = [
        ["Afar", "Semera"],
        ["Amhara", "Bahir Dar"],
        ["Benishangul-Gumuz", "Asosa"],
        ["Gambela", "Gambela"],
        ["Harari Region", "Harar"],
        ["Oromia", "Finfinne"],
        ["Somali Region", "Jijiga"],
        ["Southern Nations, Nationalities, and Peoples' Region", "Hawassa"],
        ["Tigray", "Mek'ele"]
    ]
    
    //  France Subdivision Capitals
    let franceCapitals: [[String]] = [
        ["Auvergne-Rhone-Alpes", "Lyon"],
        ["Bourgogne-Franche-Comte", "Dijon"],
        ["Brittany", "Rennes"],
        ["Centre-Val de Loire", "Orleans"],
        ["Corsica", "Ajaccio"],
        ["Grand Est", "Strasbourg"],
        ["Hauts-de-France", "Lille"],
        ["Ile-de-France", "Paris"],
        ["Normandy", "Rouen"],
        ["Nouvelle-Aquitaine", "Bordeaux"],
        ["Occitanie", "Toulouse"],
        ["Pays de la Loire", "Nantes"],
        ["Provence-Alpes-Cote d'Azur", "Marseille"]
    ]
    
    // Germany Subdivision Capitals
    let germanyCapitals: [[String]] = [
        ["Baden-Wurttemberg", "Stuttgart"],
        ["Bavaria", "Munich"],
        ["Berlin", "Berlin"],
        ["Brandenburg", "Potsdam"],
        ["Bremen", "Bremen"],
        ["Hamburg", "Hamburg"],
        ["Hesse", "Wiesbaden"],
        ["Lower Saxony", "Hanover"],
        ["Mecklenburg-Vorpommern", "Schwerin"],
        ["North Rhine-Westphalia", "Dusseldorf"],
        ["Rhineland-Palatinate", "Mainz"],
        ["Saarland", "Saarbrucken"],
        ["Saxony", "Dresden"],
        ["Saxony-Anhalt", "Magdeburg"],
        ["Schleswig-Holstein", "Kiel"],
        ["Thuringia", "Erfurt"]
    ]
    
    //  Guatemala Subdivision Capitals
    let guatemalaCapitals: [[String]] = [
        ["Alta Verapaz", "Coban"],
        ["Baja Verapaz", "Salama"],
        ["Chimaltenango", "Chimaltenango"],
        ["Chiquimula", "Chiquimula"],
        ["El Progreso", "Guastatoya"],
        ["Escuintla", "Escuintla"],
        ["Guatemala", "Guatemala City"],
        ["Huehuetenango", "Huehuetenango"],
        ["Izabal", "Puerto Barrios"],
        ["Jalapa", "Jalapa"],
        ["Jutiapa", "Jutiapa"],
        ["Peten", "Flores"],
        ["Quetzaltenango", "Quetzaltenango"],
        ["Quiche", "Santa Cruz del Quiche"],
        ["Retalhuleu", "Retalhuleu"],
        ["Sacatepequez", "Antigua Guatemala"],
        ["San Marcos", "San Marcos"],
        ["Santa Rosa", "Cuilapa"],
        ["Solola", "Solola"],
        ["Suchitepequez", "Mazatenango"],
        ["Totonicapan", "Totonicapan"],
        ["Zacapa", "Zacapa"]
    ]
    
    //  Italy Subdivision Capitals
    let italyCapitals: [[String]] = [
        ["Abruzzo", "L'Aquila"],
        ["Aosta Valley", "Aosta"],
        ["Apulia", "Bari"],
        ["Basilicata", "Potenza"],
        ["Calabria", "Catanzaro"],
        ["Campania", "Naples"],
        ["Emilia-Romagna", "Bologna"],
        ["Friuli-Venezia Giulia", "Trieste"],
        ["Lazio", "Rome"],
        ["Liguria", "Genoa"],
        ["Lombardy", "Milan"],
        ["Marche", "Ancona"],
        ["Molise", "Campobasso"],
        ["Piedmont", "Turin"],
        ["Sardinia", "Cagliari"],
        ["Sicily", "Palermo"],
        ["Trentino-South Tyrol", "Trento"],
        ["Tuscany", "Florence"],
        ["Umbria", "Perugia"],
        ["Veneto", "Venice"]
    ]
    
    //  India Subdivision Capitals
    let indiaCapitals: [[String]] = [
        ["Andaman and Nicobar Islands", "Port Blair"],
        ["Andhra Pradesh (de facto)", "Amaravati"],
        ["Arunachal Pradesh", "Itanagar"],
        ["Assam", "Dispur"],
        ["Bihar", "Patna"],
        ["Chandigarh", "Chandigarh"],
        ["Chhattisgarh", "Raipur"],
        ["Dadra and Nagar Haveli", "Silvassa"],
        ["Daman and Diu", "Edmonton"],
        ["National Capital Territory of Delhi", "New Delhi"],
        ["Goa", "Panaji"],
        ["Gujarat", "Gandhinagar"],
        ["Haryana", "Chandigarh"],
        ["Himachal Pradesh (summer)", "Shimla"],
        ["Himachal Pradesh (winter)", "Dharamshala"],
        ["Jammu and Kashmir (summer)", "Srinagar"],
        ["Jammu and Kashmir (winter)", "Jammu"],
        ["Jharkhand", "Ranchi"],
        ["Karnataka", "Bengaluru"],
        ["Kerala", "Thiruvananthapuram"],
        ["Lakshadweep", "Kavaratti"],
        ["Madhya Pradesh", "Bhopal"],
        ["Maharashtra", "Mumbai"],
        ["Manipur", "Imphal"],
        ["Meghalaya", "Shillong"],
        ["Mizoram", "Aizawl"],
        ["Nagaland", "Kohima"],
        ["Odisha", "Bhubaneswar"],
        ["Puducherry", "Puducherry"],
        ["Punjab", "Chandigarh"],
        ["Rajasthan", "Jaipur"],
        ["Sikkim", "Gangtok"],
        ["Tamil Nadu", "Chennai"],
        ["Telangana", "Hyderabad"],
        ["Tripura", "Agartala"],
        ["Uttar Pradesh", "Lucknow"],
        ["Uttarakhand", "Dehradun"],
        ["West Bengal", "Kolkata"]
    ]
    
    //  Indonesia Subdivision Capitals
    let indonesiaCapitals: [[String]] = [
        ["Aceh", "Banda Aceh"],
        ["Bali", "Denpasar"],
        ["Bangka Belitung Islands", "Pangkalpinang"],
        ["Banten", "Serang"],
        ["Bengkulu", "Bengkulu"],
        ["Central Java", "Semarang"],
        ["Central Kalimantan", "Palangka Raya"],
        ["Central Sulawesi", "Palu"],
        ["East Java", "Surabaya"],
        ["East Kalimantan", "Samarinda"],
        ["East Nusa Tenggara", "Kupang"],
        ["Gorontalo", "Gorontalo"],
        ["Special Capital Region of Jakarta", "Jakarta"],
        ["Jambi", "Jambi"],
        ["Lampung", "Bandar Lampung"],
        ["Maluku", "Ambon"],
        ["North Kalimantan", "Tanjung Selor"],
        ["North Maluku", "Sofifi"],
        ["North Sulawesi", "Manado"],
        ["North Sumatra", "Medan"],
        ["Papua", "Jayapura"],
        ["Riau", "Pekanbaru"],
        ["Riau Islands", "Tanjung Pinang"],
        ["Southeast Sulawesi", "Kendari"],
        ["South Kalimantan", "Banjarmasin"],
        ["South Sulawesi", "Makassar"],
        ["South Sumatra", "Palembang"],
        ["West Java", "Bandung"],
        ["West Kalimantan", "Pontianak"],
        ["West Nusa Tenggara", "Mataram"],
        ["West Papua", "Manokwari"],
        ["West Sulawesi", "Mamuju"],
        ["West Sumatra", "Padang"],
        ["Special Region of Yogyakarta", "Yogyakarta"]
    ]
    
    //  Iran Subdivision Capitals
    let iranCapitals: [[String]] = [
        ["Alborz", "Karaj"],
        ["Ardabil", "Ardabil"],
        ["Bushehr", "Bushehr"],
        ["Chahar Mahaal and Bakhtiari", "Shahrekord"],
        ["East Azerbaijan", "Tabriz"],
        ["Fars", "Shiraz"],
        ["Gilan", "Rasht"],
        ["Golestan", "Gorgan"],
        ["Hamadan", "Hamadan"],
        ["Hormozgan", "Bandar Abbas"],
        ["Ilam", "Ilam"],
        ["Isfahan", "Isfahan"],
        ["Kerman", "Kerman"],
        ["Kermanshah", "Kermanshah"],
        ["Khuzestan", "Ahvaz"],
        ["Kohgiluyeh and Boyer-Ahmad", "Yasuj"],
        ["Kurdistan", "Sanandaj"],
        ["Lorestan", "Khorramabad"],
        ["Markazi", "Arak"],
        ["Mazandaran", "Sari"],
        ["North Khorasan", "Bojnourd"],
        ["Qazvin", "Qazvin"],
        ["Qom", "Qom"],
        ["Razavi Khorasan", "Mashhad"],
        ["Semnan", "Semnan"],
        ["Sistan and BLuchestan", "Zahedan"],
        ["South Khorasan", "Birjand"],
        ["Tehran", "Tehran"],
        ["West Azerbaijan", "Urmia"],
        ["Yazd", "Yazd"],
        ["Zanjan", "Zanjan"]
    ]
    
    //  Japan Subdivision Capitals
    let japanCapitals: [[String]] = [
        ["Aichi (Honshu Island)", "Nagoya"],
        ["Akita (Honshu Island)", "Akita"],
        ["Aomori (Honshu Island)", "Aomori"],
        ["Chiba (Honshu Island)", "Chiba"],
        ["Ehime (Shikoku Island)", "Matsuyama"],
        ["Fukui (Honshu Island)", "Fukui"],
        ["Fukuoka (Kyushu Island)", "Fukuoka"],
        ["Fukushima (Honshu Island)", "Fukushima"],
        ["Gifu (Honshu Island)", "Gifu"],
        ["Gunma (Honshu Island)", "Maebashi"],
        ["Hiroshima (Honshu Island)", "Hiroshima"],
        ["Hokkaido (Hokkaido Island)", "Sapporo"],
        ["Hyogo (Honshu Island)", "Kobe"],
        ["Ibaraki (Honshu Island)", "Mito"],
        ["Ishikawa (Honshu Island)", "Kanazawa"],
        ["Iwate (Honshu Island)", "Morioka"],
        ["Kagawa (Shikoku Island)", "Takamatsu"],
        ["Kagoshima (Kyushu Island)", "Kagoshima"],
        ["Kanagawa (Honshu Island)", "Yokohama"],
        ["Kochi (Shikoku Island)", "Kochi"],
        ["Kumamoto (Kyushu Island)", "Kumamoto"],
        ["Kyoto (Honshu Island)", "Kyoto"],
        ["Mie (Honshu Island)", "Tsu"],
        ["Miyagi (Honshu Island)", "Sendai"],
        ["Miyazaki (Kyushu Island)", "Miyazaki"],
        ["Nagano (Honshu Island)", "Nagano"],
        ["Nagasaki (Kyushu Island)", "Nagasaki"],
        ["Nara (Honshu Island)", "Nara"],
        ["Niigata (Honshu Island)", "Niigata"],
        ["Oita (Kyushu Island)", "Oita"],
        ["Okayama (Honshu Island)", "Okayama"],
        ["Okinawa (Ryukyu Islands)", "Naha"],
        ["Osaka (Honshu Island)", "Osaka"],
        ["Saga (Kyushu Island)", "Saga"],
        ["Saitama (Honshu Island)", "Saitama"],
        ["Shiga (Honshu Island)", "Otsu"],
        ["Shimane (Honshu Island)", "Matsue"],
        ["Shizuoka (Honshu Island)", "Shizuoka"],
        ["Tochigi (Honshu Island)", "Utsunomiya"],
        ["Tokushima (Shikoku Island)", "Tokushima"],
        ["Tokyo (Honshu Island)", "Tokyo"],
        ["Tottori (Honshu Island)", "Tottori"],
        ["Toyama (Honshu Island)", "Toyama"],
        ["Wakayama (Honshu Island)", "Wakayama"],
        ["Yamagata (Honshu Island)", "Yamagata"],
        ["Yamaguchi (Honshu Island)", "Yamaguchi"],
        ["Yamanashi (Honshu Island)", "Kofu"]
    ]
    
    //  Kazakhstan Subdivision Capitals
    let kazakhstanCapitals: [[String]] = [
        ["Akmola", "Kokshetau"],
        ["Aktobe", "Aktobe"],
        ["Almaty", "Taldykorgan"],
        ["Atyrau", "Atyrau"],
        ["East Kazakhstan", "Oskemen"],
        ["Jambyl", "Taraz"],
        ["Karaganda", "Karaganda"],
        ["Kostanay", "Kostanay"],
        ["Kyzylorda", "Kyzylorda"],
        ["Mangystau", "Aktau"],
        ["North Kazakhstan", "Petropavl"],
        ["Pavlodar", "Pavlodar"],
        ["Turkistan", "Turkistan"],
        ["West Kazakhstan", "Oral"]
    ]
    
    //  Malaysia Subdivision Capitals
    let malaysiaCapitals: [[String]] = [
        ["Johor Darul Ta'zim", "Johor Bahru"],
        ["Kedah Darul Aman", "Alor Setar"],
        ["Kelantan Darul Naim", "Kota Bharu"],
        ["Kuala Lampur", "Kuala Lampur"],
        ["Labuan", "Victoria"],
        ["Malacca", "Malacca City"],
        ["Negeri Sembilan Darul Khusus", "Seremban"],
        ["Pahang Darul Makmur", "Kuantan"],
        ["Penang", "George Town"],
        ["Perak Darul Ridzuan", "Ipoh"],
        ["Perlis Indera Kayangan", "Kangar"],
        ["Putrajaya", "Putrajaya"],
        ["Sabah", "Koat Kinabalu"],
        ["Sarawak", "Kuching"],
        ["Selangor Darul Ehsan", "Shah Alam"],
        ["Terengganu Darul Iman", "Kuala Terengganu"]
    ]
    
    //  Mexico Subdivision Capitals
    let mexicoCapitals: [[String]] = [
        ["Aguascalientes", "Aguascalientes"],
        ["Baja California", "Mexicali"],
        ["Baja California Sur", "La Paz"],
        ["Campeche", "San Francisco de Campeche"],
        ["Chiapas", "Tuxtla Gutierrez"],
        ["Chihuahua", "Chihuahua"],
        ["Coahuila", "Saltillo"],
        ["Colima", "Colima"],
        ["Durango", "Victoria de Durango"],
        ["Guanajuato", "Guanajuato"],
        ["Guerrero", "Chilpancingo de los Bravo"],
        ["Hidalgo", "Pachuca"],
        ["Jalisco", "Guadalajara"],
        ["Mexico", "Toluca de Lerdo"],
        ["Mexico City", "Mexico City"],
        ["Michoacan", "Morelia"],
        ["Morelos", "Cuernavaca"],
        ["Nayarit", "Tepic"],
        ["Nuevo Leon", "Monterrey"],
        ["Oaxaca", "Oaxaca de Juarez"],
        ["Puebla", "Pueblo de Zaragoza"],
        ["Queretaro", "Santiago de Queretaro"],
        ["Quintana Roo", "Chetumal"],
        ["San Luis Potosi", "San Luis Potosi"],
        ["Sinaloa", "Culiacan"],
        ["Sonora", "Hermosillo"],
        ["Tabasco", "Villahermosa"],
        ["Tamaulipas", "Ciudad Victoria"],
        ["Tlaxcala", "Tlaxcala"],
        ["Veracruz", "Xalapa"],
        ["Yucatan", "Merida"],
        ["Zacatecas", "Zacatecas"]
    ]
    
    //  Myanmar Subdivision Capitals
    let myanmarCapitals: [[String]] = [
        ["Ayeyarwady", "Pathein"],
        ["Bago", "Bago"],
        ["Chin", "Hakha"],
        ["Danu", "Pindaya"],
        ["Kachin", "Myitkyina"],
        ["Kayah", "Loikaw"],
        ["Kayin", "Pa-an"],
        ["Kokang", "Laukkai"],
        ["Magway", "Magway"],
        ["Mandalay", "Mandalay"],
        ["Mon", "Mawlamyine"],
        ["Naga", "Lahe"],
        ["Naypyidaw", "Naypyidaw"],
        ["Pa Laung", "Namhsan"],
        ["Pa'O", "Hopong"],
        ["Rakhine", "Sittwe"],
        ["Shan", "Taunggyi"],
        ["Sagaing", "Sagaing"],
        ["Tanintharyi", "Dawei"],
        ["Wa", "Hopang"],
        ["Yangon", "Yangon"]
    ]
    
    //  Nigeria Subdivision Capitals
    let nigeriaCapitals: [[String]] = [
        ["Abia", "Umuahia"],
        ["Adamawa", "Yola"],
        ["Akwa Ibom", "Uyo"],
        ["Anambra", "Awka"],
        ["Bauchi", "Bauchi"],
        ["Bayelsa", "Yenagoa"],
        ["Benue", "Makurdi"],
        ["Borno", "Maiduguri"],
        ["Cross River", "Calabar"],
        ["Delta", "Asaba"],
        ["Ebonyi", "Abakaliki"],
        ["Edo", "Benin"],
        ["Ekiti", "Ado Ekiti"],
        ["Enugu", "Enugu"],
        ["Federal Capital Territory", "Abuja"],
        ["Gombe", "Gombe"],
        ["Imo", "Owerri"],
        ["Jigawa", "Dutse"],
        ["Kaduna", "Kaduna"],
        ["Kano", "Kano"],
        ["Katsina", "Katsina"],
        ["Kebbi", "Birnin Kebbi"],
        ["Kogi", "Lokoja"],
        ["Kwara", "Ilorin"],
        ["Lagos", "Ikeja"],
        ["Nasarawa", "Lafia"],
        ["Niger", "Minna"],
        ["Ogun", "Abeokuta"],
        ["Ondo", "Akure"],
        ["Osun", "Oshogbo"],
        ["Oyo", "Ibadan"],
        ["Plateau", "Jos"],
        ["Rivers", "Port Harcourt"],
        ["Sokoto", "Sokoto"],
        ["Taraba", "Jalingo"],
        ["Yobe", "Damaturu"],
        ["Zamfara", "Gusau"]
    ]
    
    //  Pakistan Subdivision Capitals
    let pakistanCapitals: [[String]] = [
        ["Azad Jammu and Kashmir", "Muzaffarabad"],
        ["Baluchistan", "Quetta"],
        ["Gilgit-Baltistan", "Gilgit"],
        ["Islamabad Capital Territory", "Islamabad"],
        ["Khyber Pakhtunkhwa", "Peshawar"],
        ["Punjab", "Lahore"],
        ["Sindh", "Karachi"]
    ]
    
    //  Peru Subdivision Capitals
    let peruCapitals: [[String]] = [
        ["Amazonas", "Chachapoyas"],
        ["Ancash", "Huaraz"],
        ["Apurimac", "Abancay"],
        ["Arequipa", "Arequipa"],
        ["Ayacucho", "Ayacucho"],
        ["Cajamarca", "Cajamarca"],
        ["Callao", "Callao"],
        ["Cusco", "Cusco"],
        ["Huancavelica", "Huancavelica"],
        ["Huanuco", "Huanaco"],
        ["Ica", "Ica"],
        ["Junin", "Huancayo"],
        ["La Libertad", "Trujillo"],
        ["Lambayeque", "Chiclayo"],
        ["Lima", "Huacho"],
        ["Loreto", "Iquitos"],
        ["Madre de Dios", "Puerto Maldonado"],
        ["Moquegua", "Moquegua"],
        ["Pasco", "Cerro de Pasco"],
        ["Piura", "Piura"],
        ["Puno", "Puno"],
        ["San Martin", "Moyobamba"],
        ["Tacna", "Tacna"],
        ["Tumbes", "Tumbes"],
        ["Ucayali", "Pucallpa"]
    ]
    
    //  Russia Subdivision Capitals
    let russiaCapitals: [[String]] = [
        ["Adygea", "Maykop"],
        ["Bashkortostan", "Ufa"],
        ["Buryatia", "Ulan-Ude"],
        ["Altai Republic", "Goroi-Altaysk"],
        ["Dagestan", "Makhachkala"],
        ["Ingushetia", "Magas"],
        ["Kabardino-Balkaria", "Nalchik"],
        ["Kalmykia", "Elista"],
        ["Karachay-Cherkessia", "Cherkessk"],
        ["Karelia", "Petrozavodsk"],
        ["Komi Republic", "Syktyvkar"],
        ["Mari El Republic", "Yoshkar-Ola"],
        ["Mordovia", "Saransk"],
        ["Sakha Republic (Yakutia)", "Yakutsk"],
        ["North Ossetia-Alania", "Vladikavkaz"],
        ["Tatarstan", "Kazan"],
        ["Tuva Republic", "Kyzyl"],
        ["Udmurt Republic", "Izhevsk"],
        ["Khakassia", "Abakan"],
        ["Chechenya", "Grozny"],
        ["Chuvash Republic", "Cheboksary"],
        ["Altai Krai", "Barnaul"],
        ["Krasnodar Krai", "Krasnodar"],
        ["Krasnoyarsk Krai", "Krasnoyarsk"],
        ["Primorsky Krai", "Vladivosok"],
        ["Stavropol Krai", "Stavropol"],
        ["Khabarovsk Krai", "Khabarovsk"],
        ["Amur Oblast", "Blagoveshchensk"],
        ["Arkhangelsk Oblast", "Arkhangelsk"],
        ["Astrakhan Oblast", "Astrakhan"],
        ["Belgorod Oblast", "Belgorod"],
        ["Bryansk Oblast", "Bryansk"],
        ["Vladimir Oblast", "Vladimir"],
        ["Volgograd Oblast", "Volgograd"],
        ["Vologda Oblast", "Vologda"],
        ["Voronezh Oblast", "Voronezh"],
        ["Ivanovo Oblast", "Ivanovo"],
        ["Irkutsk Oblast", "Irkutsk"],
        ["Kaliningrad Oblast", "Kaliningrad"],
        ["Kaluga Oblast", "Kaluga"],
        ["Kemerovo Oblast", "Kemerovo"],
        ["Kirov Oblast", "Kirov"],
        ["Kostroma Oblast", "Kostroma"],
        ["Kurgan Oblast", "Kurgan"],
        ["Kursk Oblast", "Kursk"],
        ["Lipetsk Oblast", "Lipetsk"],
        ["Magadan Oblast", "Magadan"],
        ["Murmansk Oblast", "Murmansk"],
        ["Nizhny Novgorod Oblast", "Nizhny Novgorod"],
        ["Novgorod Oblast", "Veliky Novgorod"],
        ["Novosibirsk Oblast", "Novosibirsk"],
        ["Omsk Oblast", "Omsk"],
        ["Orenburg Oblast", "Orenburg"],
        ["Oryol Oblast", "Oryol"],
        ["Penza Oblast", "Penza"],
        ["Pskov Oblast", "Pskov"],
        ["Rostov Oblast", "Rostov-on-Don"],
        ["Ryazan Oblast", "Ryazan"],
        ["Samara Oblast", "Samara"],
        ["Saratov Oblast", "Saratov"],
        ["Sakhalin Oblast", "Yuzhno-Sakhalinsk"],
        ["Sverdlovsk Oblast", "Yekaterinburg"],
        ["Smolensk Oblast", "Smolensk"],
        ["Tambov Oblast", "Tambov"],
        ["Tver Oblast", "Tver"],
        ["Tomsk Oblast", "Tomsk"],
        ["Tula Oblast", "Tula"],
        ["Tyumen Oblast", "Tyumen"],
        ["Ulyanovsk Oblast", "Ulyanovsk"],
        ["Chelyabinsk Oblast", "Chelyabinsk"],
        ["Yaroslavl Oblast", "Yaroslavl"],
        ["Jewish Autonomous Oblast", "Birobidzhan"],
        ["Nenets Autonomous Okrug", "Naryan-Mar"],
        ["Khanty-Mansi Autonomous Okrug (Yugra)", "Khanty-Mansiysk"],
        ["Chukotka Autonomous Okrug", "Anadyr"],
        ["Yamalo-Nenets Autonomous Okrug", "Salekhard"],
        ["Perm Krai", "Perm"],
        ["Kamchatka Krai", "Petropavlovsk-Kamchatsky"],
        ["Zabaykalsky Krai", "Chita"],
        ["Crimea", "Simferopol"]
    ]
    
    //  Saudi Arabia Subdivision Capitals
    let saudiArabiaCapitals: [[String]] = [
        ["'Asir", "Abha"],
        ["Bahah", "Al-Bahah"],
        ["Eastern Province", "Dammam"],
        ["Ha'il", "Ha'il"],
        ["Jawf", "Sakakah"],
        ["Jizan", "Jizan"],
        ["Madinah (hint: submit transliterated answer)", "Madinah"],
        ["Makkah (hint: submit transliterated answer)", "Makkah"],
        ["Najran", "Najran"],
        ["Northern Borders", "Arar"],
        ["Qassim", "Buraidah"],
        ["Riyadh", "Riyadh"],
        ["Tabuk", "Tabuk"]
    ]
    
    //  South Africa Subdivision Capitals
    let southafricaCapitals: [[String]] = [
        ["Eastern Cape Province", "Bhisho"],
        ["Free State Province", "Bloemfontein"],
        ["Guateng Province", "Johannesburg"],
        ["KwaZulu-Natal Province", "Pietermaritzburg"],
        ["Limpopo Province", "Polokwane"],
        ["Mpumalanga Province", "Mbombela"],
        ["North West Province", "Mahikeng"],
        ["Northern Cape Province", "Kimberley"],
        ["Western Cape Province", "Cape Town"]
    ]
    
    //  Spain Subdivision Capitals
    let spainCapitals: [[String]] = [
        ["Andalusia", "Seville"],
        ["Catalonia", "Barcelona"],
        ["Community of Madrid", "Madrid"],
        ["Valencian Community", "Valencia"],
        ["Galicia", "Santiago de Compostela"],
        ["Castile and Leon", "Valladolid"],
        ["Basque Country", "Vitoria-Gasteiz"],
        ["Castilla-La Mancha", "Toledo"],
        ["Canary Islands (Gran Canaria Island)", "Las Palmas de Grand Canaria"],
        ["Canary Islands (Tenerife Island)", "Santa Cruz de Tenerife"],
        ["Region of Murcia", "Murcia"],
        ["Aragon", "Zaragoza"],
        ["Extremadura", "Merida"],
        ["Balearic Islands", "Palma"],
        ["Asturias", "Oviedo"],
        ["Navarre", "Pamplona"],
        ["Cantabria", "Santander"],
    ]
    
    //  Sri Lanka Subdivision Capitals
    let srilankaCapitals: [[String]] = [
        ["Central Province", "Kandy"],
        ["Eastern Province", "Trincomalee"],
        ["North Central Province", "Anuradhapura"],
        ["Northern Province", "Jaffna"],
        ["North Western Province", "Kurunegala"],
        ["Sabaragamuwa Province", "Ratnapura"],
        ["Southern Province", "Galle"],
        ["Uva Province", "Badulla"],
        ["Western Province", "Colombo"]
    ]
    
    //  Tanzania Subdivision Capitals
    let tanzaniaCapitals: [[String]] = [
        ["Arusha", "Arusha"],
        ["Dar es Salaam", "Dar es Salaam"],
        ["Dodoma", "Dodoma"],
        ["Geita", "Geita"],
        ["Iringa", "Iringa"],
        ["Kagera", "Bukoba"],
        ["Katavi", "Mpanda"],
        ["Kigoma", "Kigoma"],
        ["Kilimanjaro", "Moshi"],
        ["Lindi", "Lindi"],
        ["Manyara", "Babati"],
        ["Mara", "Musoma"],
        ["Mbeya", "Mbeya"],
        ["Mjini Magharibi", "Zanzibar"],
        ["Morogoro", "Morogoro"],
        ["Mtwara", "Mtwara"],
        ["Mwanza", "Mwanza"],
        ["Njombe", "Njombe"],
        ["Pemba North", "Wete"],
        ["Pemba South", "Chake-Chake"],
        ["Pwani", "Kibaha"],
        ["Rukwa", "Sumbawanga"],
        ["Ruvuma", "Songea"],
        ["Shinyanga", "Shinyanga"],
        ["Simiyu", "Bariadi"],
        ["Singida", "Singida"],
        ["Songwe", "Vwawa"],
        ["Tabora", "Tabora"],
        ["Tanga", "Tanga"],
        ["Unguja North", "Mkokotoni"],
        ["Unguja South", "Koani"]
    ]
    
    //  Uzbekistan Subdivision Capitals
    let uzbekistanCapitals: [[String]] = [
        ["Andijan", "Andijan"],
        ["Bukhara", "Bukhara"],
        ["Fergana", "Fergana"],
        ["Jizzakh", "Jizzakh"],
        ["Xorazm", "Urgench"],
        ["Namangan", "Namangan"],
        ["Navoiy", "Navoiy"],
        ["Qashqadaryo", "Qarshi"],
        ["Samarkand", "Samarkand"],
        ["Sirdaryo", "Guliston"],
        ["Surxondaryo", "Termez"],
        ["Tashkent", "Tashkent"],
        ["Karakalpakstan", "Nukus"]
    ]
    
    //  Venezuela Subdivision Capitals
    let venezuelaCapitals: [[String]] = [
        ["Amazonas", "Puerto Ayacucho"],
        ["Anzoategui", "Barcelona"],
        ["Apure", "San Fernando de Apure"],
        ["Aragua", "Maracay"],
        ["Barinas", "Barinas"],
        ["Bolivar", "Ciudad Bolivar"],
        ["Carabobo", "Valencia"],
        ["Cojedes", "San Carlos"],
        ["Delta Amacuro", "Tucupita"],
        ["Falcon", "Coro"],
        ["Guarico", "San Juan de Los Morros"],
        ["La Guaira", "La Guaira"],
        ["Lara", "Barquisimeto"],
        ["Merida", "Merida"],
        ["Miranda", "Los Teques"],
        ["Monagas", "Maturin"],
        ["Nueva Esparta", "La Asuncion"],
        ["Portuguesa", "Guanare"],
        ["Sucre", "Cumana"],
        ["Tachira", "San Cristobal"],
        ["Trujillo", "Trujillo"],
        ["Yaracuy", "San Felipe"],
        ["Zulia", "Maracaibo"],
        ["Capital District", "Caracas"],
        ["Fedreal Dependencies", "Los Roques"]
    ]
}
