//
//  MultipleChoice.swift
//  GeoGuru
//
//  Created by Pranav and Keshav Ramesh on 9/8/18.
//  Copyright © 2018 GeoGuru. All rights reserved.
//

import UIKit

class MultipleChoice {
    
    // Array format: ["question", "choice1", "choice2", "correct answer (could be choice 1 or 2)"]
    
    var MultipleChoice: [[String]] = []
//        ["The Lewis and Clark Expedition explored which region from 1804 to 1806 – Louisiana Purchase or Southwest?","Louisiana Purchase","Southwest","Louisiana Purchase"],
//        ["Lake Sakakawea is a 200-mile-long reservoir along which river – Missouri River or Colorado River?","Missouri River","Colorado River","Missouri River"],
//        ["What city, founded by William Penn, was the site of the First and Second Continental Congresses – Baltimore or Philadelphia?","Baltimore","Philadelphia","Philadelphia"],
//        ["Which one of the contiguous United States has the northernmost point – Minnesota or Wisconsin?","Minnesota","Wisconsin","Minnesota"],
//        ["Which city is more likely to have desert vegetation – Phoenix or Denver?","Phoenix","Denver","Phoenix"],
//        ["What city in Alabama was the subject of a 1955 and 1956 bus boycott organized by Martin Luther King, Jr., to protest bus segregation – Montgomery or Birmingham?","Montgomery","Birmingham","Montgomery"],
//        ["Which state has more coastal marshland – Louisiana or Kentucky?","Louisiana","Kentucky","Louisiana"],
//        ["Which city is in western Texas and lies directly across the border from the Mexican city of Ciudad Juarez – Amarillo or El Paso?","Amarillo","El Paso","El Paso"],
//        ["Badlands National Park and Mount Rushmore are west of the Missouri River in which state – Minnesota or South Dakota?","Minnesota","South Dakota","South Dakota"],
//        ["Which northeast state borders Canada – New Hampshire or Massachusetts?","New Hampshire","Massachusetts","New Hampshire"],
//        ["Cape Cod, known for its beautiful shoreline, is located in which state – New Jersey or Massachusetts?","New Jersey","Massachusetts","Massachusetts"],
//        ["When it's 1 p.m. in Hawaii, what part of the day is it in the state of New York – midnight or evening?","Midnight","Evening","Evening"],
//        ["Which state produces more wood pulp – Georgia or Florida?","Georgia","Florida","Georgia"],
//        ["Land bordering the mouths of the James, York, and Rappahannock Rivers is part of the Tidewater region of which state – Virginia or Ohio?","Virginia","Ohio","Virginia"],
//        ["Poi is a food commonly associated with people native to which state – Hawaii or Alaska?","Hawaii","Alaska","Hawaii"],
//        ["The Constitution State is the state nickname for what state – Connecticut or Maryland?","Connecticut","Maryland","Connecticut"],
//        ["The easternmost point in the contiguous United States is located in what state – Massachusetts or Maine?","Massachusetts","Maine","Maine"],
//        ["El Paso is a city that lies close to Mexico in what state famous for its oil production – Texas or New Mexico?","Texas","New Mexico","Texas"],
//        ["Mount St. Helens is a volcano in what state – Oregon or Washington?","Oregon","Washington","Washington"],
//        ["Chicago borders what Great Lake – Lake Michigan or Lake Huron?","Lake Michigan","Lake Huron","Lake Michigan"],
//        ["Florida, Texas, Louisiana, Alabama, and what other southeastern state border the Gulf of Mexico – Mississippi or Georgia?","Mississippi","Georgia","Mississippi"],
//        ["The Great Miami River and Little Miami River are two rivers in what state in the Eastern Time Zone – Florida or Ohio?","Florida","Ohio","Ohio"],
//        ["Cape Canaveral is located in what state – Florida or Massachusetts?","Florida","Massachusets","Florida"],
//        ["The port of Mobile is located in what state – Mississippi or Alabama?","Mississippi","Alabama","Alabama"],
//        ["In which state is more land used for agriculture – Connecticut or Illinois?","Connecticut","Illinois","Illinois"],
//        ["Which state borders California on the north – Oregon or Utah?","Oregon","Utah","Oregon"],
//        ["Newport, a prominent seaport in colonial times, is now a popular tourist area located in which state – Rhode Island or Delaware?","Rhode island","Delaware","Rhode Island"],
//        ["Brownsville, an important border city on the Rio Grande, is located in which state – New Mexico or Texas?","New Mexico","Texas","Texas"],
//        ["Which state does not have a coastline – New Mexico or New Hampshire?","New Mexico","New Hampshire","New Mexico"],
//        ["Which bay has a larger total area – Prudhoe Bay or Chesapeake Bay?","Prudhoe Bay","Chesapeake Bay","Chesapeake Bay"],
//        ["The Brooks Range is located in what state – Maine or Alaska?","Maine","Alaska","Alaska"],
//        ["Mount Whitney is the highest point in the contiguous United States, located in what state – California or Nevada?","California","Nevada","California"],
//        ["The Chilkoot Pass crosses from Alaska into what country – Canada or Mexico?","Canada","Mexico","Canada"],
//        ["The Arkansas River, a tributary of the Mississippi River, has its source in what major mountain range – Rocky Mountains or Appalachian Mountains?","Rocky Mountains","Appalachian Mountains","Rocky Mountains"],
//        ["The Great Salt Lake is located in what U.S. state home to a large population of Mormons – Utah or Wyoming?","Utah","Wyoming","Utah"],
//        ["Lake Okeechobee, on the edge of the Everglades, is located in what U.S. state with the cities of Orlando and Miami – Georgia or Florida?","Georgia","Florida","Florida"],
//        ["Chesapeake Bay is an estuary of what river – Susquehanna River or Allegheny River?","Susquehanna River","Allegheny River","Susquehanna River"],
//        ["Lake Pontchartrain is located on what plain – Great Plains or Gulf Coastal Plain?","Great Plains","Gulf Coastal Plain","Gulf Coastal Plain"],
//        ["Yosemite Falls, located in the Sierra Nevada, is in what region of the United States – southern or western?","Southern","Western","Western"],
//        ["Cape Cod and Cape Canaveral are located on what coast of the United States – West or East?","West","East","East"],
//        ["Howland Island, Jarvis Island, and Wake Island are all territories of the United States located in what ocean – Atlantic Ocean or Pacific Ocean?","Atlantic Ocean","Pacific Ocean","Pacific Ocean"],
//        ["People from Mexico and what other country constitute the highest number of immigrants to the United States every year – India or China?","India","China","India"],
//        ["Permafrost in the United States is found in what U.S. state – Montana or Alaska?","Montana","Alaska","Alaska"],
//        ["Molokai is one of the main islands of what state that was the last to join the United States – Alaska or Hawaii?","Alaska","Hawaii","Hawaii"],
//        ["Houston is a major port on what gulf – Gulf of Mexico or Gulf of Alaska?","Gulf of Mexico","Gulf of Alaska","Gulf of Mexico"],
//        ["The District of Columbia is located between Maryland and what other U.S. state – Delaware or Virginia?","Delaware","Virginia","Virginia"],
//        ["Cape Hatteras can be found off the coast of what U.S. state home to Duke University – North Carolina or South Carolina?","North Carolina","South Carolina","North Carolina"],
//        ["Long Island Sound is north of Long Island and south of what U.S. state home to the historical figures of Oliver Ellsworth and Noah Webster – Connecticut or Rhode Island?","Connecticut","Rhode Island","Connecticut"],
//        ["Glen Canyon is a hydroelectric dam on what river – Monongahela River or Colorado River?","Monongahela River","Colorado River","Colorado River"],
//        ["The Gulf of Maine feeds into what ocean – Pacific Ocean or Atlantic Ocean?","Pacific Ocean","Atlantic Ocean","Atlantic Ocean"],
//        ["Lake Michigan is the only Great Lake entirely in the United States. This lake also borders what U.S. state where the cities of Lansing and Detroit can be found – Michigan or Illinois?","Michigan","Illinois","Michigan"],
//        ["Which Great Lake is the smallest in size - Lake Ontario or Lake Erie?","Lake Ontario","Lake Erie","Lake Erie"],
//        ["The Saint Lawrence River forms part of the border between the United States and what other country – Mexico or Canada?","Mexico","Canada","Canada"],
//        ["The Seward Peninsula is located in what U.S. state whose major cities include Anchorage and Fairbanks – Alaska or Washington?","Alaska","Washington","Alaska"],
//        ["Phoenix, a major U.S. city and the capital of Arizona, is on the edge of what southwestern U.S. desert – Sonoran Desert or Chihuahuan Desert?","Sonoran Desert","Chihuahuan Desert","Sonoran Desert"],
//        ["Cape Flattery is bordered by the Pacific Ocean and what strait – Strait of Juan de Fuca or Bering Strait?","Strait of Juan de Fuca","Bering Strait","Strait of Juan de Fuca"],
//        ["The Aleutian Islands are a group of islands belonging to Alaska that extend across what meridian – 180 degree or 170 degree?","180 degree","170 degree","180 degree"],
//        ["Amarillo is a city in what U.S. state famous for its oil production – Oklahoma or Texas?","Oklahoma","Texas","Texas"],
//        ["The Straits of Florida connect the Atlantic Ocean to what gulf – Gulf of Alaska or Gulf of Mexico?","Gulf of Alaska","Gulf of Mexico","Gulf of Mexico"],
//        ["The Colorado River, emptying out into the Gulf of California, created what major canyon in Arizona – Grand Canyon or Palo Duro Canyon?","Grand Canyon","Palo Duro Canyon","Grand Canyon"],
//        ["Hoover Dam can be found on the border between Arizona and what other U.S. state known as the Silver State – Nevada or New Mexico?","Nevada","New Mexico","Nevada"],
//        ["The longest river in New England is what river – Connecticut River or Hudson River?","Connecticut River","Hudson River","Connecticut River"],
//        ["Lake Itasca can be found in what U.S. state – Mississippi or Minnesota?","Mississippi","Minnesota","Minnesota"],
//        ["Hartford, known as the insurance capital of the United States, is the capital of what U.S. state where the first hamburger was served in U.S. history – Connecticut or Rhode Island?","Connecticut","Rhode Island","Connecticut"],
//        ["Wisconsin borders what U.S. state to the east – Michigan or Illinois?","Michigan","Illinois","Michigan"],
//        ["Lake Champlain borders New York and what other U.S. state – Vermont or New Hampshire?","Vermont","New Hampshire","Vermont"],
//        ["Redwood National Park can be found in the northern part of what U.S. state – California or Oregon?","California","Oregon","California"],
//        ["Marquette and Flint are cities in what U.S. state bordering four of the Great Lakes – Wisconsin or Michigan?","Wisconsin","Michigan","Michigan"],
//        ["International Falls can be found in what U.S. state with the cities of Duluth and Rochester – Minnesota or New York?","Minnesota","New York","Minnesota"],
//        ["Cape Mendocino and Point Conception can be found in what U.S. state home to the Mojave Desert and Mount Whitney – Nevada or California?","Nevada","California","California"],
//        ["Which bay is connected to the Atlantic Ocean – Monterey Bay or Chesapeake Bay?","Monterey Bay","Chesapeake Bay","Chesapeake Bay"],
//        ["Which U.S. state has a longer border with Mexico – Texas or California?","Texas","California","Texas"],
//        ["New York is the only U.S. state that borders which lake – Lake Erie or Lake Ontario?","Lake Erie","Lake Ontario","Lake Ontario"],
//        ["Cape Cod and Cape Hatteras are along which coast of the United States – West or East?","West","East","East"],
//        ["Which state shares the longest border with Mexico – New Mexico or Texas?","New Mexico","Texas","Texas"],
//        ["The Pocono Mountains in Pennsylvania link with what mountain group to the northeast – Catskill Mountains or Adirondack Mountains?","Catskill Mountains","Adirondack Mountains","Catskill Mountains"],
//        ["Which U.S. state is located closer to the Tropic of Cancer – Louisiana or Maine?","Louisiana","Maine","Louisiana"],
//        ["Which U.S. state has more people per square mile, or a greater population density – Indiana or New Mexico?","Indiana","New Mexico","Indiana"],
//        ["Redwoods, the world's tallest trees, are found in which U.S. state – California or Alaska?","California","Alaska","California"],
//        ["Which river forms the eastern boundary of Missouri – Mississippi River or Arkansas River?","Mississippi River","Arkansas River","Mississippi River"],
//        ["Which U.S. state has more national wildlife refuges – Oregon or Kentucky?","Oregon","Kentucky","Oregon"],
//        ["Which U.S. state has a larger population – Connecticut or West Virginia?","Connecticut","West Virginia","Connecticut"],
//        ["The Mississippi River separates Tennessee from which state—Arkansas or Oklahoma?","Arkansas","Oklahoma","Arkansas"],
//        ["Which U.S. state is north of the Ohio River—Virginia or Indiana?","Virginia","Indiana","Indiana"],
//        ["What state, known as the Centennial State, joined the United States in 1876—Colorado or Vermont? ","Colorado","Vermont","Colorado"],
//        ["What river forms most of the border between Georgia and South Carolina—Potomac River or Savannah River?","Potomac River","Savannah River","Savannah River"],
//        ["Which city lies near the confluence of the Missouri and Mississippi Rivers—Memphis or St. Louis?","Memphis","St. Louis","St. Louis"],
//        ["What agricultural state contains the geographical center of North America—New Jersey or North Dakota? ","New Jersey","North Dakota","North Dakota"],
//        ["Farmers in what state use water from the Ogallala Aquifer for irrigation—Nebraska or Maine? ","Nebraska","Maine","Nebraska"],
//        ["Which city is the westernmost point on the Erie Canal—Cincinnati or Buffalo?","Cincinnati","Buffalo","Buffalo"],
//        ["Which major city is located in North Carolina and was near the site of the first important gold discovery in the United States—Columbia or Charlotte?","Columbia","Charlotte","Charlotte"],
//        ["Which city lies along the Willamette River – Portland or Sacramento?","Portland","Sacramento","Portland"],
//        ["Which U.S. state has the lowest per capita income – Texas or Mississippi?","Texas","Mississippi","Mississippi"],
//        ["Which lake is the largest in the United States west of the Mississippi River – Great Salt Lake or Lake Mead?","Great Salt Lake","Lake Mead","Great Salt Lake"],
//        ["What state has a larger Native American population – Oklahoma or Maryland?","Oklahoma","Maryland","Oklahoma"],
//        ["What state reaches farther north – Wyoming or West Virginia?","Wyoming","West Virginia","Wyoming"],
//        ["What state has more people per square mile – Connecticut or Kentucky?","Connecticut","Kentucky","Connecticut"],
//        ["The Great Basin can be found in what state – Nevada or Utah?","Nevada","Utah","Nevada"],
//        ["Which U.S. state borders Lake Erie – Pennsylvania or Illinois?","Pennsylvania","Illinois","Pennsylvania"],
//        ["Which city is located in the eastern part of Washington State – Spokane or Auburn?","Spokane","Auburn","Spokane"],
//        ["Roanoke is in what present day U.S. state bordering Chesapeake Bay – Virginia or Maryland?","Virginia","Maryland","Virginia"],
//        ["Long Island Sound borders what U.S. state to the north – New York or Connecticut?","New York","Connecticut","Connecticut"],
//        ["Block Island is a famous island belonging to what U.S. state with the capital city of Providence – Rhode Island or Vermont?","Rhode Island","Vermont","Rhode Island"],
//        ["Which river runs between Arizona and California before entering Mexico – Platte River or Colorado River?","Platte River","Colorado River","Colorado River"],
//        ["What state is adjacent to the Gulf of Mexico – Mississippi or Georgia?","Mississippi","Georgia","Mississippi"],
//        ["What city is located in an arid climate zone – Santa Fe or Milwaukee?","Santa Fe","Milwaukee","Santa Fe"],
//        ["What city is famous for its steep hills and cable cars – San Francisco or San Antonio?","San Francisco","San Antonio","San Francisco"],
//        ["What mountainous state includes Rocky Mountain National Park— Montana or Colorado?","Montana","Colorado","Colorado"],
//        ["Parliament Hill, site of Canadian national government buildings, is in which city – Ottawa or Montreal?","Ottawa","Montreal","Ottawa"],
//        ["The Lempa River, which flows into the Pacific Ocean, provides hydroelectric power in which Central American country – El Salvador or Guatemala?","El Salvador","Guatemala","El Salvador"],
//        ["Prince Rupert's Land is a historic region that made up much of which present day country in the Western Hemisphere – Canada or Argentina?","Canada","Argentina","Canada"],
//        ["Stromboli is to Italy as Popocatepetl is to what – Mexico or Guatemala?","Mexico","Guatemala","Mexico"],
//        ["What country has the third largest area in the world – Mexico or United States?","Mexico","United States","United States"],
//        ["The ports of Anchorage, Vancouver, and Acapulco are along which coast of North America – West or East?","West","East","West"],
//        ["Hispaniola consists of the Dominican Republic and what other country – Jamaica or Haiti?","Jamaica","Haiti","Haiti"],
//        ["Curacao is the largest island in what Antilles – Netherlands Antilles or Lesser Antilles?","Netherlands Antilles","Lesser Antilles","Netherlands Antilles"],
//        ["Saint Barthelemy is located in what North American region – Caribbean or Central America?","Caribbean","Central America","Caribbean"],
//        ["Prince Edward Island is the smallest province in what country – Canada or the Bahamas?","Canada","Bahamas","Canada"],
//        ["The Yucatan Peninsula is located in what country – Panama or Mexico?","Panama","Mexico","Mexico"],
//        ["The Turks and Caicos Islands belong to what European country – United Kingdom or France?","United Kingdom","France","United Kingdom"],
//        ["The Statue of Liberty, a gift from France, is located in what U.S. State – New York or California?","New York","California","New York"],
//        ["Aruba, Bonaire, and Curacao are part of what region of the Caribbean – Lesser Antilles or Netherlands Antilles?","Lesser Antilles","Netherlands Antilles","Netherlands Antilles"],
//        ["Oranjestad is the capital of what Dutch Territory in the Caribbean – Bonaire or Aruba?","Bonaire","Aruba","Aruba"],
//        ["St. Pierre and Miquelon is a territory of France nearest to what country – Canada or the United States?","Canada","United States","Canada"],
//        ["Ellesmere Island and Baffin Island are two large islands in what country – Mexico or Canada?","Mexico","Canada","Canada"],
//        ["The Beaufort Sea is located north of Canada and a U.S. state. Name this state – Hawaii or Alaska?","Hawaii","Alaska","Alaska"],
//        ["The Great Northern Peninsula, which extends approximately 170 miles from Bonne Bay on the west to Cape Bauld at the tip, is located in Newfoundland in which country – Canada or the United States?","Canada","United States","Canada"],
//        ["What large island is located 200 miles northwest of Iceland – Baffin Island or Greenland?","Baffin Island","Greenland","Greenland"],
//        ["The largest metropolitan area in North America, is also the capital of a country. Name this metropolitan area – Washington D.C. or Mexico City?","Washington D.C.","Mexico City","Mexico City"],
//        ["What is the most densely populated country in North America, located in the Caribbean with the capital of Bridgetown – Trinidad and Tobago or Barbados?","Trinidad and Tobago","Barbados","Barbados"],
//        ["Activity along the San Andreas Fault in North America helped create which peninsula – Baja California or Yucatan Peninsula?","Baja Claifornia","Yucatan Peninsula","Baja California"],
//        ["Which of these Caribbean islands is closest to the Tropic of Cancer – Cuba or Grenada?","Cuba","Grenada","Cuba"],
//        ["The island of Newfoundland is located off the east coast of Canada in which ocean – Atlantic Ocean or Pacific Ocean?","Altlantic Ocean","Pacific Ocean","Atlantic Ocean"],
//        ["If you were in Chicago, Illinois, which would you be closest to – Tropic of Cancer or Tropic of Capricorn?","Tropic of Cancer","Tropic of Capricorn","Tropic of Cancer"],
//        ["What is another name for the Falkland Islands, a territory of the United Kingdom located east of Argentina – Islas Malvinas or the British Isles?","Islas Malvinas","British isles","Islas Malvinas"],
//        ["Los Llanos is a large tropical grassland plain in Venezuela and what other country straddling the Sierra Nevada de Santa Marta, the world’s highest coastal range – Colombia or Guyana?","Colombia","Guyana","Colombia"],
//        ["Which country has a drier climate - Argentina or Colombia?","Argentina","Colombia","Argentina"],
//        ["Which country is not bordered by the Orinoco River – Colombia or Ecuador?","Colombia","Ecuador","Ecuador"],
//        ["Which South American country was a member of OPEC until 1992 – Ecuador or Chile?","Ecuador","Chile","Ecuador"],
//        ["Which Indian state has the highest literacy rate in India – Jharkhand or Kerala?","Jharkhand","Kerala","Kerala"],
//        ["Which country is the most populous in Asia – China or Indonesia?","China","Indonesia","China"],
//        ["The Kizilirmak River is also known as what river – Huang He or Halys River?","Huang He","Halys River","Halys River"],
//        ["Which country has the capital of Ulaanbaatar – Uzbekistan or Mongolia?","Uzbekistan","Mongolia","Mongolia"],
//        ["The island of Bali is home to the largest proportion of the Hindu minority in which Southeast Asian country – Malaysia or Indonesia?","Malaysia","Indonesia","Indonesia"],
//        ["Dushanbe, Astana, and Tashkent are capitals of three countries that are located in what region – Southwest Asia or Central Asia?","Southwest Asia","Central Asia","Central Asia"],
//        ["The Tigris and Euphrates Rivers are located in what present day country that used to contain Mesopotamia, one of the first civilizations in the world – Iran or Iraq?","Iran","Iraq","Iraq"],
//        ["The Republic of China is known by what other name – Hong Kong or Taiwan?","Hong Kong","Taiwan","Taiwan"],
//        ["Kuwait was invaded by Iraq in what year – 1990 or 1992?","1990","1992","1990"],
//        ["Which sea is the Earth’s lowest elevation on land – Red Sea or Dead Sea?","Red Sea","Dead Sea","Dead Sea"],
//        ["The Irtysh River is located in what country – Kazakhstan or Kyrgyzstan?","Kazakhstan","Kyrgyzstan","Kazakhstan"],
//        ["The ancient Phoenicians lived in which present day country – Lebanon or Israel?","Lebanon","Israel","Lebanon"],
//        ["Kyrgyzstan occupies part of what mountain range – Ural Mountains or Tian Shan?","Ural Mountains","Tian Shan","Tian Shan"],
//        ["Which country is an example of an archipelago – Maldives or Bangladesh?","Maldives","Bangladesh","Maldives"],
//        ["What is the fourth largest religion in Malaysia – Hinduism or Jainism?","Hinduism","Jainism","Hinduism"],
//        ["The Angara River is located in the Irkutsk Oblast in what country – China or Russia?","China","Russia","Russia"],
//        ["Many people speak Russian in what country– North Korea or Kazakhstan?","North Korea","Kazakhstan","Kazakhstan"],
//        ["The Arabian Sea is west of India, and the Bay of Bengal is in what position relative to India – East or North?","East","North","East"],
//        ["Mohenjo-Daro and Harappa were cities along what river civilization – Ancient India or Ancient China?","Ancient India","Ancient China","Ancient India"],
//        ["The Chao Phraya River flows into the Gulf of Thailand and is a major river of what country – Thailand or Cambodia?","Thailand","Cambodia","Thailand"],
//        ["Turkmenistan borders what country to the northeast – Tajikistan or Uzbekistan?","Tajikistan","Uzbekistan","Uzbekistan"],
//        ["The Tibetan Plateau can be found in the country of China, north of what mountain range with mountains that are the highest in the world – Himalayas or the Kunlun Shan?","Himalayas","Kunlun Shan","Himalayas"],
//        ["Buddhism is practiced by a little over 70% of the population of what country – Maldives or Sri Lanka?","Maldives","Sri Lanka","Sri Lanka"],
//        ["Adam’s Bridge connects two countries, India and what other country – Sri Lanka or Maldives?","Sri Lanka","Maldives","Sri Lanka"],
//        ["The Malay Peninsula is found in what region – Central Asia or Southeast Asia?","Central Asia","Southeast Asia","Southeast Asia"],
//        ["The Amur River forms part of the border between China and what other country – Mongolia or Russia?","Mongolia","Russia","Russia"],
//        ["Which country is not landlocked – North Korea or Nepal?","North Korea","Nepal","North Korea"],
//        ["Which country that is made up of islands spans more degrees of longitude – Seychelles or Maldives?","Seychelles","Maldives","Maldives"],
//        ["The Kara Darya is a tributary of what major river – Amu Darya or Syr Darya?","Amu Darya","Syr Darya","Syr Darya"],
//        ["The West Bank, the Shatt al Arab, and Kashmir are all disputed regions on which continent – Asia or Africa?","Asia","Africa","Asia"],
//        ["Which river flows from its source on the Tibetan Plateau through Pakistan before draining into the Arabian Sea – Indus River or Ganges River?","Indus River","Ganges River","Indus River"],
//        ["Most of the world's highest mountains are part of which mountain system – Himalayas or Andes?","Himalayas","Andes","Himalayas"],
//        ["Which country has more arable land – Cambodia or Qatar?","Cambodia","Qatar","Cambodia"],
//        ["Estonia, Latvia, and Lithuania are known by what name – Scandinavia or the Baltic States?","Scandinavia","Baltic States","Baltic States"],
//        ["Albania borders what country to the east – Macedonia or Croatia?","Macedonia","Croatia","Macedonia"],
//        ["Canary Wharf, part of the Docklands redevelopment, is located on what European river that rises in the Cotswold Hills – Thames River or Volga River?","Thames River","Volga River","Thames River"],
//        ["Many legal terms come from the language of ancient Rome. Name this language – Latin or Altaic?","Latin","Altaic","Latin"],
//        ["Which mountains extend across more degrees of latitude – Apennines or Ural Mountains?","Apennines","Ural Mountains","Ural Mountains"],
//        ["Lake Ohrid and Lake Prespa are located in what country north of Greece – Macedonia or Bulgaria?","Macedonia","Bulgaria","Macedonia"],
//        ["Hungarian is closely related to what language spoken in Finland – Swedish or Finnish?","Swedish","Finnish","Finnish"],
//        ["The Salisbury Plain in southwestern England is the site of what famous Neolithic monument – Big Bentley or Stonehenge?","Big Bentley","Stonehenge","Stonehenge"],
//        ["Sweden's highest peak, Kebnekaise, is located in the Kjölen Mountains. These mountains run along Sweden's boundary with which country – Norway or Denmark?","Norway","Denmark","Norway"],
//        ["Which country is more densely populated – Netherlands or Russia?","Netherlands","Russia","Netherlands"],
//        ["The Great Dividing Range is to Australia as the Grampian Mountains are to what – Scotland or Germany?","Scotland","Germany","Scotland"],
//        ["Which country borders the Baltic Sea – Latvia or Romania?","Latvia","Romania","Latvia"],
//        ["Which country has more boreal forests – Finland or Costa Rica?","Finland","Costa Rica","Finland"],
//        ["Which country, known for its fjords, has the longest coastline in Europe – Finland or Norway?","Finland","Norway","Norway"],
//        ["What is another name for Cote d’ Ivoire – Cape Verde or Ivory Coast?","Cape Verde","Ivory Coast","Ivory Coast"],
//        ["Western Sahara is a disputed region in what area of Africa – West Africa or Southern Africa?","West Africa","Southern Africa","West Africa"],
//        ["Which continent includes the Atlas Mountains and the Kalahari Desert – Africa or South America?","Africa","South America","Africa"],
//        ["A swampy region in northern Africa, known as the Sudd, is drained by tributaries of which river – Nile River or Zambezi River?","Nile River","Zambezi River","Nile River"],
//        ["Gabon, Chad, Congo, and the Central African Republic were once part of which region – French West Africa or French Equatorial Africa?","French West Africa","French Equatorial Africa","French Equatorial Africa"],
//        ["The Waitomo Caves can be found in what country containing the city of Queenstown, a major tourist attraction – Solomon Islands or New Zealand?","Solomon Islands","New Zealand","New Zealand"],
//        ["Nuku’alofa is the capital of what country in the South Pacific – Tonga or Tokelau?","Tonga","Tokelau","Tonga"],
//        ["The Marshall Islands and Kiribati are countries in what region – Micronesia or Melanesia?","Micronesia","Melanesia","Micronesia"],
//        ["What is New Caledonia’s climate more similar to – tropical or arid?","Tropical","Arid","Tropical"],
//        ["Antarctica is located in what line of latitude – the Arctic Circle or the Antarctic Circle?","Arctic Circle","Antarctic Circle","Antarctic Circle"],
//        ["What station in Antarctica had the coldest temperature on record on Earth – Amundsen-Scott South Pole Station or Vostok Station?","Amundsen-Scott South Pole Station","Vostok Station","Vostok Station"],
//        ["Excluding Antarctica, which continent is the least populous – South America or Australia and Oceania?","South America","Australia and Oceania","Australia"],
//        ["Antarctica’s “population” mainly consists of who – Researchers or Meteorologists?","Researchers","Meteorologists","Researchers"],
//        ["What continent lies closest to Antarctica – Australia and Oceania or South America?","Australia and Oceania","South America","South America"],
//        ["Vinson Massif, the highest point in Antarctica, is located in what mountain range – Transantarctic Mountains or Ellsworth Mountains?","Transantarctic Mountains","Ellsworth Mountains","Ellsworth Mountains"],
//        ["Mount Erebus is an active volcano on what island – Deception Island or Ross Island?","Deception Island","Ross Island","Ross Island"],
//        ["Plateau Station in Antarctica belongs to what country – United States or Russia?","United States","Russia","United States"],
//        ["The Antarctic Treaty was signed in 1959 by how many countries – thirteen or twelve?","Thirteen","Twelve","Twelve"],
//        ["What explorer named Mount Erebus after one of his ships – Roald Amundsen or James Clark Ross?","Roald Amundsen","James Clark Ross","James Clark Ross"],
//        ["What ocean surrounds Antarctica completely – Southern Ocean or Indian Ocean?","Southern Ocean","Indian Ocean","Southern Ocean"],
//        ["What is it called at the place where the Pacific, Atlantic, and Indian Oceans meet the Antarctic Circumpolar Current – Antarctic Convergence or Antarctic Peninsula?","Antarctic Convergence","Antarctic Peninsula","Antarctic Convergence"],
//        ["Cape Crozier borders the Ross Sea and what other body of water – McMurdo Sound or Prydz Bay?","McMurdo Sound","Prydz Bay","McMurdo Sound"],
//        ["Bentley Subglacial Trench is the lowest point in Antarctica, located in Marie Byrd Land and near what mountain range – Shackleton Mountains or Ellsworth Mountains?","Shackleton Mountains","Ellsworth Mountains","Ellsworth Mountains"],
//        ["Roosevelt Island is located on what ice shelf – Ross Ice Shelf or Ronne Ice Shelf?","Ross Ice Shelf","Ronne Ice Shelf","Ross Ice Shelf"],
//        ["The Riiser-Larsen Peninsula borders what bay to the southeast – Porpoise Bay or Lutzow-Holm Bay?","Porpoise Bay","Lutzow-Holm Bay","Lutzow-Holm Bay"],
//        ["Joinville Island can be found off the coast of what peninsula – Antarctic Peninsula or Riiser-Larsen Peninsula?","Antarctic Peninsula","Riiser-Larsen Peninsula","Antarctic Peninsula"],
//        ["Mt. Minto can be found on what cape – Cape Adare or Cape Poinsett?","Cape Adare","Cpae Poinsett","Cape Adare"],
//        ["Alexander Island borders what sea – Weddell Sea or Bellingshausen Sea?","Weddell Sea","Bellingshausen Sea","Bellingshausen Sea"],
//        ["Roosevelt Island is surrounded by an Antarctic ice sheet that shares its name with what nearby sea – Weddell Sea or Ross Sea?","Weddell Sea","Ross Sea","Ross Sea"],
//        ["The Bellingshausen Sea and the Ross Sea border which continent – Australia and Oceania or Antarctica?","Australia and Oceania","Antarctica","Antarctica"],
//        ["The South Shetland Islands, which are claimed by the United Kingdom, Chile, and Argentina, are off the coast of which continent – Antarctica or Asia?","Antarctica","Asia","Antarctica"],
//        ["What term describes the air circulation pattern of rising air at the Equator and sinking air around 30 degrees latitude – Hadley Cell or Westerly?","Hadley Cell","Westerly","Hadley Cell"],
//        ["Which commonly serves as the baseline for measuring elevations of Earth's landforms – sea level or river level?","Sea Level","River Level","Sea Level"],
//        ["What is the term for the process by which ice sheets expand and reshape the physical landscape – Weathering or Glaciation?","Weathering","Glaciation","Glaciation"],
//        ["What resource is trapped between layers of rock in an aquifer – Water or Oil?","Water","Oil","Water"],
//        ["What is created when lightning suddenly heats the air, causing it to expand rapidly – Thunder or Rain?","Thunder","Rain","Thunder"],
//        ["How many degrees of latitude are there south of the Equator – 90 degrees or 180 degrees?","90 degrees","180 degrees","90 degrees"],
//        ["Seismology is the study of what – Volcanoes or Earthquakes?","Volcanoes","Earthquakes","Earthquakes"],
//        ["What is the term for a navigable waterway connecting two larger bodies of water – Strait or Bay?","Strait","Bay","Strait"],
//        ["What is the term for the lower limit of permanent snow cover on a mountain – snowline or treeline?","Snowline","Treeline","Snowline"],
//        ["Which is the term for the frozen ground in Arctic areas where soil temperatures remain below freezing most or all of the year – permafrost or desert?","Permafrost","Permafrost","Permafrost"],
//        ["The tropopause marks the boundary between the troposphere and which other layer of the atmosphere – stratosphere or mesosphere?","Stratosphere","Mesosphere","Stratosphere"],
//        ["What is the term for a huge desert area characterized by deep sand dunes – Erg or Harmattan?","Erg","Harmattan","Erg"],
//        ["What type of stone is composed mainly of calcite and is a sedimentary rock – Sandstone or Limestone?","Sandstone","Limestone","Limestone"],
//        ["A line on a map connecting points that receive equal precipitation is known by what name – Isohyet or Isobar?","Isohyet","Isobar","Isohyet"],
//        ["Which characteristic is shared by all deserts – low precipitation or many sand dunes?","Low Precipitation","Many Sand Dunes","Low Precipitation"],
//        ["What is the term used to describe a tropical grassland home to widely spaced trees – delta or savanna?","Delta","Savanna","Savanna"],
//        ["What does a barometer measure – wind direction or atmospheric pressure?","Wind Direction","Atmospheric Pressure","Atmospheric Pressure"],
//        ["Cenotes, or sinkholes such as those found on the Yucatán Peninsula, are associated with which rock—basalt or limestone? ","Basalt","Limestone","Limestone"],
//        ["Bandar Seri Begawan is the capital of what Southeast Asian country whose official languages are Malay and English – East Timor or Brunei?","East Timor","Brunei","Brunei"],
//        ["Kaliningrad Oblast is an exclave of what country that hosted the Sochi 2014 Winter Olympics – Ukraine or Russia?","Ukraine","Russia","Russia"],
//        ["The Asian Games is an Asian multi-sport event held every four years in different locations. Which country holds the record for the most gold medals – Japan or China?","Japan","China","China"],
//        ["Nepal and Bhutan are countries both whose two most practiced religions are Hinduism and Buddhism, religions that originated in what present day country – India or Bangladesh?","Indiana","Bangladesh","India"],
//        ["Mecca and Medina are holy Islamic cities in what country on the Arabian Peninsula – Saudi Arabia or Yemen?","Saudi Arabia","Yemen","Saudi Arabia"],
//        ["The Olympic Games were invented in what country that was home to the ancient Minoans – Greece or Turkey?","Greece","Turkey","Greece"],
//        ["The kora, which is a musical instrument made from a gourd, is often played in Gambia on which continent – Africa or Asia?","Africa","Asia","Africa"],
//        ["Muslims in the city of Mopti pray at mosques constructed of clay around a wooden frame. Mopti is southeast of Mauritania in what country – Mali or Senegal?","Mali","Senegal","Mali"],
//        ["The principal Christian denomination in Egypt shares its name with a form of the ancient Egyptian language. Name this denomination – Coptic Christian or Roman Catholic?","Coptic Christian","Roman Catholic","Coptic Christian"],
//        ["Couscous is a popular dish from the northern part of which continent – Africa or Europe?","Africa","Europe","Africa"],
//        ["The Han are the most populous ethnic group in which mainland Asian country – Thailand or China?","Thailand","China","China"],
//        ["The island of Honshu can be found in what country, home to many followers of Shintoism – South Korea or Japan?","South Korea","Japan","Japan"],
//        ["Finnish and Swedish are languages spoken in the Aland Islands, a territory of what Nordic country – Finland or Sweden?","Finland","Sweden","Finland"],
//        ["St. Basil's Cathedral, located in Red Square, is an Orthodox church in which country – Ukraine or Russia?","Ukraine","Russia","Russia"],
//        ["Shintoism is what type of religion – polytheistic or monotheistic?","Polytheistic","Monotheistic","Polytheistic"],
//        ["What is the largest sect of Christianity – Protestant or Roman Catholic?","Protestant","Roman Catholic","Roman Catholic"],
//        ["The rulers of the Mughal Empire in India were followers of what religion – Hinduism or Islam?","Hinduism","Islam","Islam"],
//        ["Xhosa and Zulu are languages spoken in what country in Africa that is famous for its penguins – South Africa or Madagascar?","South Africa","Madagascar","South Africa"],
//        ["The Khmer Empire followed mostly Hinduism and a little of what other religion – Buddhism or Confucianism?","Buddhism","Confucianism","Buddhism"],
//        ["Kannada is a language spoken in South India, from what language group – Austroasiatic or Dravidian?","Austroasiatic","Dravidian","Dravidian"],
//        ["Mandarin Chinese, Spanish, English, Arabic, Russian, and what other language are the six official languages of the United Nations – French or German? ","French","German","French"],
//        ["Which state has a larger Asian-American population – California or Utah?","California","Utah","California"],
//        ["Which language is derived from ancient Celtic – Basque or Welsh?","Basque","Welsh","Welsh"],
//        ["Santos, a major coffee-exporting port, is on the Atlantic coast of what country – Costa Rica or Brazil?","Costa Rica","Brazil","Brazil"],
//        ["What is the term for a marketplace in Middle Eastern and North African cities where a variety of goods is sold – Bazaar or Salam?","Bazaar","Salam","Bazaar"],
//        ["The production of maple syrup is an important economic activity in which state – Vermont or Utah?","Vermont","Utah","Vermont"],
//        ["Coffee is a major export of what country in North America – Haiti or Canada?","Haiti","Canada","Haiti"],
//        ["What country is the largest exporter of bananas – Ecuador or Chile?","Ecuador","Chile","Ecuador"],
//        ["The economy of Brunei, a small country on the island of Borneo, is based on offshore oil and natural gas fields that lie beneath which ocean – Indian Ocean or Pacific Ocean?","Indian Ocean","Pacific Ocean","Pacific Ocean"],
//        ["Which country has a higher life expectancy rate – Australia or Ukraine?","Australia and Oceania","Ukraine","Australia"],
//        ["Which country does not have a high population density – Australia or Bangladesh?","Australia and Oceania","Bangladesh","Australia"],
//        ["Which state produces more apples – Washington or Mississippi?","Washington","Mississippi","Washington"],
//        ["Which country has a greater amount of proven oil reserves – United Arab Emirates or South Korea?","United Arab Emirates","South Korea","United Arab Emirates"],
//        ["Which capital city, located on the Mediterranean Sea, is an important port for Libya – Tripoli or Mogadishu?","Tripoli","Mogadishu","Tripoli"],
//        ["Pakistan and India are currently in a dispute over what territory – Kashmir or Punjab?","Kashmir","Punjab","Kashmir"],
//        ["Eritrea gained independence from Ethiopia in what year – 1992 or 1993?","1992","1993","1993"],
//        ["The United States bought Alaska from what country – Canada or Russia?","Canada","Russia","Russia"],
//        ["Zionism is a political movement that led to the creation of what country in the Middle East in 1948 – Israel or Jordan?","Israel","Jordan","Israel"],
//        ["The boundary between the United States and Russia passes between which archipelago in the Bering Strait – Kuril Islands or Diomede Islands?","Kuril Islands","Diomede Islands","Diomede Islands"],
//        ["The partially recognized republic of Abkhazia is northwest of what country whose capital is Tbilisi – Georgia or Armenia?","Georgia","Armenia","Georgia"],
//        ["Which country currently hosts a larger refugee population – Spain or Jordan?","Spain","Jordan","Jordan"],
//        ["Which of the following cities is the oldest city on the Korean Peninsula and the seat of a communist government – Pyongyang or Seoul?","Pyongyang","Seoul","Pyongyang"],
//        ["In 1911, a revolution that began in Wuhan overthrew the imperialist government of what country – China or Mongolia?","China","Mongolia","China"],
//        ["In 1979 the Ayatollah Khomeini declared which Middle Eastern country an Islamic Republic after the ruling shah was forced to flee – Saudi Arabia or Iran?","Saudi Arabia","Iran","Iran"],
//        ["Which city was built during the 1960s to become the capital of Pakistan – Islamabad or Rawalpindi?","Islamabad","Rawalpindi","Islamabad"],
//        ["What country has more time zones – Russia or India?","Russia","Indian Ocean","Russia"],
//        ["The most famous library of ancient times was located in what Egyptian city – Cairo or Alexandria?","Cairo","Alexandria","Alexandria"],
//        ["Mahatma Gandhi fought for India’s independence from what country through nonviolence – Australia or the United Kingdom?","Australia","United Kingdom","United Kingdom"],
//        ["The Mayflower and the Titanic are two famous ships that began their transatlantic journeys at what British port city – Southampton or Plymouth?","Southampton","Plymouth","Plymouth"],
//        ["The Lewis and Clark expedition of 1804 to 1806 began at the mouth of the Missouri River and ended at the mouth of what other North American river – Columbia River or Snake River?","Columbia River","Snake River","Columbia River"],
//        ["Teotihuacán was the great center of an early civilization on which continent – North America or South America?","North America","South America","North America"],
//        ["Which European explorer was the first to see the Pacific Ocean – Balboa or Magellan?","Balboa","Magellan","Balboa"],
//        ["In what year did Bangladesh gain independence from Pakistan – 1971 or 1981?","1971","1981","1971"],
//        ["Vasco de Gama sailed around what continent to get to India – Europe or Africa?","Europe","Africa","Africa"],
//        ["Montezuma was killed by whom – Spanish Conquistadors or the British Empire?","Spanish Conquistadors","British Empire","Spanish Conquistadors"],
//        ["The Inca lived on the western coast of what continent – North America or South America?","North America","South America","South America"],
//        ["Chichen Itza was a famous monument and is now a tourist attraction in what country – Mexico or Guatemala?","Mexico","Guatemala","Mexico"],
//        ["Lewis and Clark traveled through which present day state as they explored the Louisiana Purchase – North Dakota or Louisiana?","North Dakota","Louisiana","North Dakota"],
//        ["The Louvre first opened as a museum during the French Revolution in what year – 1794 or 1793?","1794","1793","1794"],
//        ["Which country has a smaller population today than it had in the 1840s – Switzerland or Ireland?","Switzerland","Ireland","Ireland"],
//        ["Which Arctic animal has traditionally played an important role in the economy and lifestyle of the Sami – reindeer or polar bear?","Reindeer","Polar Bear","Reindeer"],
//        ["The yak, a kind of long-haired ox, is used as a pack animal in the mountain regions of which continent – Europe or Asia?","Europe","Asia","Asia"],
//        ["The Bengal tiger can be found in Nepal, Bangladesh, Myanmar, Bhutan, and what other country where the Eastern Ghats can be found – India or Pakistan?","India","Pakistan","India"],
//        ["What animal that lives south of the Sahara feeds on termites and is nocturnal – Anteater or Aardvark?","Anteater","Aardvark","Aardvark"],
//        ["Kinkajous can be found in and live in what biome – tropical rainforest or mountain forest?","Tropical Rainforest","Mountain Forest","Tropical Rainforest"],
//        ["Gir Forest National Park, in the state of Gujarat is in what country home to only 411 Asiatic Lions left in the world – India or Nepal?","India","Nepal","India"],
//        ["Which Canadian province is home to Banff National Park, a popular tourist stop – Alberta or Manitoba?","Alberta","Manitoba","Alberta"],
//        ["Tongass National Forest is located in what U.S. state – Hawaii or Alaska?","Hawaii","Alaska","Alaska"],
//        ["Angkor is a World Heritage Site in what region of Asia – South Asia or Southeast Asia?","South Asia","Southeast Asia","Southeast Asia"],
//        ["Scientists study tigers at Way Kumbas National Park on the southeastern coast of Sumatra. What sea borders this park – South China Sea or Java Sea?","South China Sea","Java Sea","Java Sea"],
//        ["Known for its cliff dwellings, Canyon de Chelly National Monument is located in which U.S. state – Colorado or Arizona?","Colorado","Arizona","Colorado"],
//        ["Many plants in Monteverde Cloud Forest Preserve get water both from rainfall and the mist that hangs in the air. This preserve is located south of Nicaragua in what country – Costa Rica or Honduras?","Costa Rica","Honduras","Costa Rica"],
//        ["Cradle Mountain-Lake St. Clair National Park, which is located northwest of the city of Hobart, is on an island that is part of what country – New Zealand or Australia?","New Zealand","Australia and Oceania","Australia"],
//        ["Royal Chitwan National Park, the site of a tiger-habitat restoration project, is in the foothills of the most populous Himalayan kingdom. Name this country – Nepal or India?","Nepal","India","Nepal"],
//        ["Lake Wallenpaupack and Allegheny National Forest can be found in what U.S. state – Ohio or Pennsylvania?","Ohio","Pennsylvania","Pennsylvania"],
//        ["Blackwater National Wildlife Refuge and William Preston Lane Jr. Memorial Bridge are landmarks in what U.S. state bordering the Potomac River – Maryland or Virginia?","Maryland","Virginia","Maryland"],
//        ["Stellwagen Bank National Marine Sanctuary and Nantucket Sound can be found bordering one U.S. state. Name this state that borders Buzzards Bay – Connecticut or Massachusetts?","Connecticut","Massachusetts","Massachusetts"],
//        ["Landscape Arch, one of the world's longest natural arches, is found at Arches National Park in which U.S. state – Arizona or Utah?","Arizona","Utah","Utah"],
//        ["Which state is a bigger producer of cheese – Wisconsin or Idaho?","Wisconsin","Idaho","Wisconsin"],
//        ["Amarillo and El Paso are cities found in what state that borders Mexico and the Gulf of Mexico – Oklahoma or Texas?","Oklahoma","Texas","Texas"],
//        ["Puget Sound can be found in what western state bordering British Columbia – Washington or Oregon?","Washington","Oregon","Washington"],
//        ["Oahu is an island belonging to what state made up of islands – Hawaii or Alaska?","Hawaii","Alaska","Hawaii"],
//        ["Chesapeake Bay empties out into what ocean – Atlantic Ocean or Pacific Ocean?","Atlantic Ocean","Pacific Ocean","Atlantic Ocean"],
//        ["What state has a shorter coastline on the Gulf of Mexico – Florida or Alabama?","Florida","Alabama","Alabama"],
//        ["What state is made up of two peninsulas – Connecticut or Michigan?","Connecticut","Michigan","Michigan"],
//        ["Rhode Island is south of Massachusetts and east of what state with the cities of New Haven and Waterbury – Connecticut or New York?","Connecticut","New York","Connecticut"],
//        ["Oswego, New York is on what Great Lake – Lake Ontario or Lake Erie?","Lake Ontario","Lake Erie","Lake Ontario"],
//        ["Minnesota borders North Dakota and what other state to its west – Montana or South Dakota?","Montana","South Dakota","South Dakota"],
//        ["The Aleutian Islands, in the North Pacific Ocean and the Bering Sea, belong to what state – Hawaii or Alaska?","Hawaii","Alaska","Alaska"],
//        ["What state borders Quebec – Pennsylvania or New Hampshire?","Pennsylvania","New Hampshire","New Hampshire"]
//    ]
}
